/-
Copyright (c) 2026 Rémy Degenne. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Rémy Degenne
-/
module

public import Ito2026Adversarial.LeanMachineLearning.Game.RepeatedGame
public import Ito2026Adversarial.LeanMachineLearning.SelfNormalized
public import Mathlib.Probability.Moments.SubGaussian

/-!
# Concentration of the rewards in a repeated game

In a run `(X, Y, Rw)` of a player against an adaptive opponent in the repeated game
(`Learning.RepeatedGame`), the reward `Rw n` of round `n` is drawn from the reward kernel `R n`
given the first `n` rounds and the two actions `(X n, Y n)` of round `n`. When the reward kernel has
conditional mean `u` and rewards in `[-1, 1]`, the noise `Rw n - u (X n) (Y n)` is conditionally
`1`-sub-Gaussian (Hoeffding's lemma) with respect to the filtration `preRewardFiltration` generated
by the first `n` rounds and the actions of round `n`. Features of the action pairs are predictable
for this filtration, so the self-normalized bound of `SelfNormalized.lean` applies.

## Main definitions

* `preReward X Y Rw n`: the first `n` rounds of the run and the two actions of round `n`;
* `preRewardFiltration`: the filtration generated by `preReward X Y Rw n`.

## Main statements

* `RewardKernel.hasSubgaussianMGF_sub`: the noise of a reward kernel with conditional mean `u`
  and rewards in `[-1, 1]` is `1`-sub-Gaussian;
* `Learning.IsAlgEnvSeq.lintegral_preReward_reward`: the reward of round `n` has conditional law
  `R n` given `preReward X Y Rw n`;
* `Learning.IsAlgEnvSeq.isCondSubgaussianNoise_preRewardFiltration`: the noise is conditionally
  `1`-sub-Gaussian;
* `Learning.IsAlgEnvSeq.probReal_forall_mahalanobisSq_inv_regGram_le_ge`: the self-normalized bound
  for the features `f (X s) (Y s)` of the action pairs and the noise of the rewards.

## Tags

repeated game, sub-Gaussian noise, self-normalized bound, filtration
-/

@[expose] public section

open MeasureTheory ProbabilityTheory Finset Real Matrix
open scoped ENNReal NNReal

namespace Learning.RepeatedGame

variable {𝒳 𝒴 : Type*} [MeasurableSpace 𝒳] [MeasurableSpace 𝒴]

/-- **Bounded noise is sub-Gaussian** (Hoeffding's lemma). If the reward kernel `R` has conditional
mean `u` and rewards in `[-1, 1]`, the noise `r - u x y` of the reward `r ∼ R n (h, x, y)` is
`1`-sub-Gaussian. -/
lemma RewardKernel.hasSubgaussianMGF_sub {R : RewardKernel 𝒳 𝒴} [∀ n, IsMarkovKernel (R n)]
    {u : 𝒳 → 𝒴 → ℝ} (hR : R.HasMean u) (hR' : R.RewardsIn (Set.Icc (-1) 1)) (n : ℕ)
    (h : Hist Unit 𝒳 (𝒴 × ℝ) n) (x : 𝒳) (y : 𝒴) :
    HasSubgaussianMGF (fun r ↦ r - u x y) 1 (R n (h, x, y)) := by
  have h1 := hasSubgaussianMGF_of_mem_Icc (μ := R n (h, x, y)) (X := id) aemeasurable_id
    (hR' n h x y)
  have hmean : (R n (h, x, y))[id] = u x y := hR n h x y
  have hc : ((‖(1 : ℝ) - -1‖₊ / 2) ^ 2 : ℝ≥0) = 1 := by
    ext
    simp only [NNReal.coe_pow, NNReal.coe_div, coe_nnnorm, NNReal.coe_ofNat, NNReal.coe_one]
    norm_num
  rw [hc, hmean] at h1
  simpa using h1

variable {Ω : Type*} {mΩ : MeasurableSpace Ω} {X : ℕ → Ω → 𝒳} {Y : ℕ → Ω → 𝒴} {Rw : ℕ → Ω → ℝ}

/-- The first `n` rounds of the run `(X, Y, Rw)` and the two actions of round `n`: what is
determined before the reward of round `n` is drawn. -/
def preReward (X : ℕ → Ω → 𝒳) (Y : ℕ → Ω → 𝒴) (Rw : ℕ → Ω → ℝ) (n : ℕ) (ω : Ω) :
    Hist Unit 𝒳 (𝒴 × ℝ) n × 𝒳 × 𝒴 :=
  (history (fun _ _ ↦ ()) X (fun t ω ↦ (Y t ω, Rw t ω)) n ω, X n ω, Y n ω)

/-- `preReward X Y Rw n` is measurable for a measurable run. -/
lemma measurable_preReward (hX : ∀ n, Measurable (X n)) (hY : ∀ n, Measurable (Y n))
    (hR : ∀ n, Measurable (Rw n)) (n : ℕ) : Measurable (preReward X Y Rw n) := by
  unfold preReward
  have : Measurable (history (fun _ _ ↦ ()) X (fun t ω ↦ (Y t ω, Rw t ω)) n) :=
    measurable_history (fun _ ↦ measurable_const) hX (fun t ↦ (hY t).prodMk (hR t)) n
  fun_prop

/-- The filtration generated by the first `n` rounds of the run and the two actions of round `n`
(`preReward X Y Rw n`). The actions of round `n` are `n`-measurable, and the reward of round `n`
is `(n + 1)`-measurable. -/
def preRewardFiltration (hX : ∀ n, Measurable (X n)) (hY : ∀ n, Measurable (Y n))
    (hR : ∀ n, Measurable (Rw n)) : Filtration ℕ mΩ where
  seq n := MeasurableSpace.comap (preReward X Y Rw n) inferInstance
  mono' n m hnm := by
    simp only
    rw [← measurable_iff_comap_le]
    rcases eq_or_lt_of_le hnm with rfl | hlt
    · exact measurable_iff_comap_le.mpr le_rfl
    have : preReward X Y Rw n =
        (fun p : Hist Unit 𝒳 (𝒴 × ℝ) m × 𝒳 × 𝒴 ↦
          ((fun i : Fin n ↦ p.1 (Fin.castLE hnm i)), (p.1 ⟨n, hlt⟩).action,
            (p.1 ⟨n, hlt⟩).feedback.1)) ∘ preReward X Y Rw m := rfl
    rw [this]
    exact measurable_comp_comap _ (by fun_prop)
  le' n := by
    rw [← measurable_iff_comap_le]
    exact measurable_preReward hX hY hR n

variable (hX : ∀ n, Measurable (X n)) (hY : ∀ n, Measurable (Y n)) (hR : ∀ n, Measurable (Rw n))

/-- The `n`-th σ-algebra of `preRewardFiltration` is generated by `preReward X Y Rw n`. -/
lemma preRewardFiltration_eq_comap (n : ℕ) :
    preRewardFiltration hX hY hR n = MeasurableSpace.comap (preReward X Y Rw n) inferInstance :=
  rfl

/-- `preReward X Y Rw n` is measurable for the `n`-th σ-algebra of `preRewardFiltration`. -/
lemma measurable_preReward_preRewardFiltration (n : ℕ) :
    Measurable[preRewardFiltration hX hY hR n] (preReward X Y Rw n) :=
  measurable_iff_comap_le.mpr le_rfl

/-- The action `X n` of the player is `n`-measurable for `preRewardFiltration`. -/
lemma measurable_action_preRewardFiltration (n : ℕ) :
    Measurable[preRewardFiltration hX hY hR n] (X n) :=
  (measurable_fst.comp measurable_snd).comp (measurable_preReward_preRewardFiltration hX hY hR n)

/-- The action `Y n` of the opponent is `n`-measurable for `preRewardFiltration`. -/
lemma measurable_opp_preRewardFiltration (n : ℕ) :
    Measurable[preRewardFiltration hX hY hR n] (Y n) :=
  (measurable_snd.comp measurable_snd).comp (measurable_preReward_preRewardFiltration hX hY hR n)

/-- The reward `Rw n` of round `n` is `(n + 1)`-measurable for `preRewardFiltration`. -/
lemma measurable_reward_preRewardFiltration_succ (n : ℕ) :
    Measurable[preRewardFiltration hX hY hR (n + 1)] (Rw n) := by
  have : Rw n = (fun p : Hist Unit 𝒳 (𝒴 × ℝ) (n + 1) × 𝒳 × 𝒴 ↦
      (p.1 (Fin.last n)).feedback.2) ∘ preReward X Y Rw (n + 1) := rfl
  rw [this]
  exact measurable_comp_comap _ (by fun_prop)

omit hX hY hR in
/-- **Conditional law of the reward.** In a run of the player `alg` against the opponent `opp`
with reward kernel `R`, the reward of round `n` has conditional law `R n` given the first `n`
rounds and the actions of round `n`: for every measurable `F ≥ 0`,
`E[F(preReward n, Rw n)] = E[∫ F(preReward n, r) dR n (preReward n)(r)]`. -/
lemma _root_.Learning.IsAlgEnvSeq.lintegral_preReward_reward {R : RewardKernel 𝒳 𝒴}
    [∀ n, IsMarkovKernel (R n)]
    {opp : Player 𝒴 𝒳} {alg : Player 𝒳 𝒴} {P : Measure Ω} [IsFiniteMeasure P]
    (h : IsAlgEnvSeq (fun _ _ ↦ ()) X (fun t ω ↦ (Y t ω, Rw t ω)) alg (gameEnv opp R) P)
    (n : ℕ) {F : (Hist Unit 𝒳 (𝒴 × ℝ) n × 𝒳 × 𝒴) × ℝ → ℝ≥0∞} (hF : Measurable F) :
    ∫⁻ ω, F (preReward X Y Rw n ω, Rw n ω) ∂P =
      ∫⁻ ω, ∫⁻ r, F (preReward X Y Rw n ω, r) ∂(R n (preReward X Y Rw n ω)) ∂P := by
  have hcd := h.hasCondDistrib_feedback n
  set Z : Ω → (Hist Unit 𝒳 (𝒴 × ℝ) n × Unit) × 𝒳 :=
    fun ω ↦ ((history (fun _ _ ↦ ()) X (fun t ω ↦ (Y t ω, Rw t ω)) n ω, ()), X n ω) with hZ
  set κ := (gameEnv opp R).feedback n with hκ
  set g : ((Hist Unit 𝒳 (𝒴 × ℝ) n × Unit) × 𝒳) × 𝒴 → Hist Unit 𝒳 (𝒴 × ℝ) n × 𝒳 × 𝒴 :=
    fun q ↦ (q.1.1.1, q.1.2, q.2) with hg
  have hgm : Measurable g := by fun_prop
  set Φ : ((Hist Unit 𝒳 (𝒴 × ℝ) n × Unit) × 𝒳) × (𝒴 × ℝ) → ℝ≥0∞ :=
    fun p ↦ F (g (p.1, p.2.1), p.2.2) with hΦ
  set Ψ : ((Hist Unit 𝒳 (𝒴 × ℝ) n × Unit) × 𝒳) × (𝒴 × ℝ) → ℝ≥0∞ :=
    fun p ↦ ∫⁻ r, F (g (p.1, p.2.1), r) ∂(R n (g (p.1, p.2.1))) with hΨ
  have hΦm : Measurable Φ := hF.comp ((hgm.comp (by fun_prop)).prodMk (by fun_prop))
  have hΨm : Measurable Ψ := by
    have : Measurable fun q ↦ ∫⁻ r, F (q, r) ∂(R n q) := hF.lintegral_kernel_prod_right'
    exact this.comp (hgm.comp (by fun_prop))
  have hpair : Measurable fun ω ↦ (Z ω, (Y n ω, Rw n ω)) :=
    ((h.measurable_history n).prodMk measurable_const |>.prodMk (h.measurable_action n)).prodMk
      (h.measurable_feedback n)
  have hmap : P.map (fun ω ↦ (Z ω, (Y n ω, Rw n ω))) = P.map Z ⊗ₘ κ := hcd.map_eq
  have key : ∀ G : ((Hist Unit 𝒳 (𝒴 × ℝ) n × Unit) × 𝒳) × (𝒴 × ℝ) → ℝ≥0∞, Measurable G →
      ∫⁻ ω, G (Z ω, (Y n ω, Rw n ω)) ∂P = ∫⁻ z, ∫⁻ yr, G (z, yr) ∂κ z ∂(P.map Z) := by
    intro G hG
    rw [← lintegral_map hG hpair, hmap, Measure.lintegral_compProd hG]
  have hL : ∫⁻ ω, F (preReward X Y Rw n ω, Rw n ω) ∂P =
      ∫⁻ ω, Φ (Z ω, (Y n ω, Rw n ω)) ∂P := rfl
  have hR' : ∫⁻ ω, ∫⁻ r, F (preReward X Y Rw n ω, r) ∂(R n (preReward X Y Rw n ω)) ∂P =
      ∫⁻ ω, Ψ (Z ω, (Y n ω, Rw n ω)) ∂P := rfl
  rw [hL, hR', key Φ hΦm, key Ψ hΨm]
  refine lintegral_congr fun z ↦ ?_
  simp only [hκ, gameEnv]
  rw [Kernel.lintegral_compProd _ _ _ (f := fun yr ↦ Φ (z, yr))
      (hΦm.comp measurable_prodMk_left),
    Kernel.lintegral_compProd _ _ _ (f := fun yr ↦ Ψ (z, yr)) (hΨm.comp measurable_prodMk_left)]
  refine lintegral_congr fun y ↦ ?_
  simp only [Kernel.comap_apply, hΨ, lintegral_const, measure_univ, mul_one, hΦ]
  rfl

/-- **The noise of the rewards is conditionally `1`-sub-Gaussian** with respect to the filtration
`preRewardFiltration` generated by the first `n` rounds and the actions of round `n`, when the
reward kernel has conditional mean `u` and rewards in `[-1, 1]`. -/
lemma _root_.Learning.IsAlgEnvSeq.isCondSubgaussianNoise_preRewardFiltration {R : RewardKernel 𝒳 𝒴}
    [∀ n, IsMarkovKernel (R n)] {opp : Player 𝒴 𝒳} {alg : Player 𝒳 𝒴} {P : Measure Ω}
    [IsFiniteMeasure P]
    (h : IsAlgEnvSeq (fun _ _ ↦ ()) X (fun t ω ↦ (Y t ω, Rw t ω)) alg (gameEnv opp R) P)
    {u : 𝒳 → 𝒴 → ℝ} (hu : Measurable (Function.uncurry u)) (hRu : R.HasMean u)
    (hR' : R.RewardsIn (Set.Icc (-1) 1)) :
    IsCondSubgaussianNoise (preRewardFiltration hX hY hR)
      (fun n ω ↦ Rw n ω - u (X n ω) (Y n ω)) P := by
  intro n g c hg hc
  rw [preRewardFiltration_eq_comap] at hg hc
  obtain ⟨g', hg'm, rfl⟩ := hg.exists_eq_measurable_comp
  obtain ⟨c', hc'm, rfl⟩ := hc.exists_eq_measurable_comp
  set F : (Hist Unit 𝒳 (𝒴 × ℝ) n × 𝒳 × 𝒴) × ℝ → ℝ≥0∞ := fun p ↦
    g' p.1 * ENNReal.ofReal (rexp (c' p.1 * (p.2 - u p.1.2.1 p.1.2.2))) with hF
  have hum : Measurable fun q : Hist Unit 𝒳 (𝒴 × ℝ) n × 𝒳 × 𝒴 ↦ u q.2.1 q.2.2 :=
    hu.comp (measurable_fst.comp measurable_snd |>.prodMk (measurable_snd.comp measurable_snd))
  have hFm : Measurable F := by
    refine (hg'm.comp measurable_fst).mul (ENNReal.measurable_ofReal.comp
      (measurable_exp.comp ?_))
    exact (hc'm.comp measurable_fst).mul (measurable_snd.sub (hum.comp measurable_fst))
  have hLHS : ∫⁻ ω, (g' ∘ preReward X Y Rw n) ω *
      ENNReal.ofReal (rexp ((c' ∘ preReward X Y Rw n) ω * (Rw n ω - u (X n ω) (Y n ω)))) ∂P =
      ∫⁻ ω, F (preReward X Y Rw n ω, Rw n ω) ∂P := rfl
  rw [hLHS, h.lintegral_preReward_reward n hFm]
  refine lintegral_mono fun ω ↦ ?_
  set q := preReward X Y Rw n ω
  have hsg := RewardKernel.hasSubgaussianMGF_sub hRu hR' n q.1 q.2.1 q.2.2
  simp only [hF, Function.comp_apply]
  rw [lintegral_const_mul (g' q) (f := fun r ↦ ENNReal.ofReal (rexp (c' q * (r - u q.2.1 q.2.2))))
    (by fun_prop)]
  gcongr
  rw [← ofReal_integral_eq_lintegral_ofReal (hsg.integrable_exp_mul (c' q))
    (ae_of_all _ fun _ ↦ (exp_pos _).le)]
  refine ENNReal.ofReal_le_ofReal ?_
  have := hsg.mgf_le (c' q)
  simpa [mgf] using this

omit hX hY hR in
/-- **The self-normalized bound for the rewards of a repeated game.** In a run of the player `alg`
against the opponent `opp` with a reward kernel of conditional mean `u` and rewards in `[-1, 1]`,
for any feature map `f` of the action pairs, with `a_s = f (X s) (Y s)` and the noise
`ε_s = Rw s - u (X s) (Y s)`, with probability at least `1 - δ`, for all `n`,
`‖∑_{s < n} ε_s a_s‖²_{V_n⁻¹} ≤ 2 log(1/δ) + log(det V_n / λ^d)` where
`V_n = λ I + ∑_{s < n} a_s a_sᵀ`. -/
lemma _root_.Learning.IsAlgEnvSeq.probReal_forall_mahalanobisSq_inv_regGram_le_ge
    {ι : Type*} [Fintype ι] [DecidableEq ι] {R : RewardKernel 𝒳 𝒴} [∀ n, IsMarkovKernel (R n)]
    {opp : Player 𝒴 𝒳} {alg : Player 𝒳 𝒴} {P : Measure Ω} [IsProbabilityMeasure P]
    (h : IsAlgEnvSeq (fun _ _ ↦ ()) X (fun t ω ↦ (Y t ω, Rw t ω)) alg (gameEnv opp R) P)
    {u : 𝒳 → 𝒴 → ℝ} (hu : Measurable (Function.uncurry u)) (hRu : R.HasMean u)
    (hR' : R.RewardsIn (Set.Icc (-1) 1)) (f : 𝒳 → 𝒴 → EuclideanSpace ℝ ι)
    (hf : Measurable (Function.uncurry f)) {lam δ : ℝ} (hlam : 0 < lam) (hδ : 0 < δ) :
    1 - δ ≤ P.real {ω | ∀ n,
      mahalanobisSq (regGram lam (fun s ↦ f (X s ω) (Y s ω)) n)⁻¹
          (∑ s ∈ range n, (Rw s ω - u (X s ω) (Y s ω)) • f (X s ω) (Y s ω)) ≤
        2 * log (1 / δ) +
          log ((regGram lam (fun s ↦ f (X s ω) (Y s ω)) n).det / lam ^ Fintype.card ι)} := by
  have hX : ∀ n, Measurable (X n) := h.measurable_action
  have hY : ∀ n, Measurable (Y n) := fun n ↦ (h.measurable_feedback n).fst
  have hR : ∀ n, Measurable (Rw n) := fun n ↦ (h.measurable_feedback n).snd
  set 𝓕 := preRewardFiltration hX hY hR
  have hXY : ∀ n, Measurable[𝓕 n] fun ω ↦ (X n ω, Y n ω) := fun n ↦
    (measurable_action_preRewardFiltration hX hY hR n).prodMk
      (measurable_opp_preRewardFiltration hX hY hR n)
  refine Learning.probReal_forall_mahalanobisSq_inv_regGram_le_ge (𝓕 := 𝓕)
    (a := fun n ω ↦ f (X n ω) (Y n ω)) (ε := fun n ω ↦ Rw n ω - u (X n ω) (Y n ω))
    (fun n ↦ hf.comp (hXY n)) (fun n ↦ ?_)
    (h.isCondSubgaussianNoise_preRewardFiltration hX hY hR hu hRu hR') hlam hδ
  exact (measurable_reward_preRewardFiltration_succ hX hY hR n).sub
    (hu.comp ((hXY n).mono (𝓕.mono n.le_succ) le_rfl))

end Learning.RepeatedGame
