module

public import Mathlib.MeasureTheory.Order.Lattice
public import Mathlib.Analysis.Convex.Basic
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.Normed.Lp.MeasurableSpace
public import Mathlib.Geometry.Convex.ConvexSpace.CompactSpaceStdSimplex
public import Mathlib.Data.Matrix.Mul
public import Mathlib.Order.ConditionallyCompleteLattice.Finset
public import Mathlib.Analysis.SpecialFunctions.Log.Basic
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Inner
public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.CategoryTheory.Countable
public import Mathlib.MeasureTheory.Constructions.Polish.Basic
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.Probability.Kernel.Composition.CompProd
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Algebra.BigOperators.Intervals
public import Mathlib.Analysis.Calculus.Gradient.Basic
public import Mathlib.Analysis.Calculus.LineDeriv.Basic
public import Mathlib.Analysis.Convex.Function
public import Mathlib.Topology.Algebra.Module.ContinuousLinearMap.PiProd
public import Mathlib.Probability.Distributions.Bernoulli
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Analysis.Matrix.MeasurableSpace
public import Mathlib.Analysis.RCLike.Lemmas
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Complex
public import Mathlib.MeasureTheory.Group.Arithmetic
public import Mathlib.Topology.Instances.Matrix
public import Mathlib.LinearAlgebra.Matrix.PosDef
public import Mathlib.Analysis.Matrix.Order
public import Mathlib.Analysis.CStarAlgebra.Matrix
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.Analysis.Convex.Hull
public import Mathlib.LinearAlgebra.Matrix.SchurComplement
public import Mathlib.Analysis.Convex.Caratheodory
public import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
public import Mathlib.Topology.Algebra.Ring.Real
public import Mathlib.Analysis.SpecialFunctions.Pow.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.ContinuousLinearMap
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Basic
public import Mathlib.Analysis.InnerProductSpace.Basic
public import Mathlib.Data.EReal.Basic
public import Mathlib.Analysis.Calculus.FDeriv.Measurable
public import Mathlib.Algebra.BigOperators.Field
public import Mathlib.Probability.IdentDistrib
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.MeasureTheory.Measure.GiryMonad
public import Mathlib.MeasureTheory.Measure.Dirac.Basic
public import Mathlib.MeasureTheory.Measure.Dirac.Def
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Order

/-! # Standalone extraction for `Ito2026Adversarial.sq_entryGap_div_four_le_mixGap`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace Finset
end Finset
namespace MeasureTheory
end MeasureTheory
namespace Learning
end Learning
namespace Learning.ZeroSumGame
end Learning.ZeroSumGame
namespace ProbabilityTheory
end ProbabilityTheory
namespace Learning.RepeatedGame
end Learning.RepeatedGame
namespace Matrix
end Matrix
namespace Real
end Real
namespace Ito2026Adversarial
end Ito2026Adversarial

-- ═══ LeanMachineLearning.ForMathlib.MeasureTheory.Order.Lattice ═══
@[expose] public section
open Finset
variable {α δ : Type*} [MeasurableSpace δ] [SemilatticeInf α] {m : MeasurableSpace α} [MeasurableInf₂ α]
attribute [to_dual existing] MeasurableInf₂
end

-- ═══ Ito2026Adversarial.Mathlib.Analysis.Convex.Simplex ═══
@[expose] public section
open MeasureTheory
namespace Learning
variable {ι : Type*} [Fintype ι]

/-- The probability simplex `{p | ∀ i, 0 ≤ p i, ∑ i, p i = 1}` of `EuclideanSpace ℝ ι`. -/
def simplex (ι : Type*) [Fintype ι] : Set (EuclideanSpace ℝ ι) :=
  {p | (∀ i, 0 ≤ p i) ∧ ∑ i, p i = 1}

/-- A point of the simplex is a function on `ι`: `p i` is its `i`-th coordinate. -/
instance instCoeFunElemEuclideanSpaceRealSimplexForall : CoeFun (simplex ι) (fun _ ↦ ι → ℝ) := ⟨fun p ↦ (p : EuclideanSpace ℝ ι).ofLp⟩

end Learning
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Game.ZeroSum ═══
@[expose] public section
open Finset
namespace Learning.ZeroSumGame
variable {𝒳 𝒴 : Type*} {u : 𝒳 → 𝒴 → ℝ} {x : 𝒳} {y : 𝒴}

/-- `(x, y)` is a pure-strategy Nash equilibrium of `u`: `u x' y ≤ u x y ≤ u x y'` for all `x'`,
`y'`. -/
def IsPSNE (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) : Prop :=
  (∀ x', u x' y ≤ u x y) ∧ ∀ y', u x y ≤ u x y'

/-- The game `u` has a pure-strategy Nash equilibrium. -/
def HasPSNE (u : 𝒳 → 𝒴 → ℝ) : Prop := ∃ x y, IsPSNE u x y

/-- The pure-strategy maximin value `v* = max_x min_y u x y`. -/
noncomputable def pureMaximin (u : 𝒳 → 𝒴 → ℝ) : ℝ := ⨆ x, ⨅ y, u x y

section Mixed
variable [Fintype 𝒳] [Fintype 𝒴]

/-- The expected utility `∑ x y, p x * q y * u x y` of the mixed strategies `p` and `q`. -/
def mixedUtility (u : 𝒳 → 𝒴 → ℝ) (p : EuclideanSpace ℝ 𝒳) (q : EuclideanSpace ℝ 𝒴) : ℝ :=
  ∑ x, ∑ y, p x * q y * u x y

/-- The mixed-strategy maximin value `max_p min_q u(p, q)`, which is the value `v^Nash` of the
Nash equilibria of the game (von Neumann's minimax theorem). -/
noncomputable def nashValue (u : 𝒳 → 𝒴 → ℝ) : ℝ :=
  ⨆ p : simplex 𝒳, ⨅ q : simplex 𝒴, mixedUtility u p q

/-- The gap `Δ^mix = v^Nash - v*` between the Nash value and the pure-strategy maximin value. -/
noncomputable def mixGap (u : 𝒳 → 𝒴 → ℝ) : ℝ := nashValue u - pureMaximin u

end Mixed
end Learning.ZeroSumGame
end

-- ═══ Ito2026Adversarial.ILMTW2026.Setting ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset Learning Learning.ZeroSumGame Learning.RepeatedGame
  Matrix Real
open scoped RealInnerProductSpace
namespace Ito2026Adversarial

/-- The minimal entry gap `Δ_M = min {|a - b|, |a - c|, |b - d|, |c - d|}` of the `2 × 2` game
`(a b; c d)`. -/
noncomputable def entryGap (u : Fin 2 → Fin 2 → ℝ) : ℝ :=
  min (min |u 0 0 - u 0 1| |u 0 0 - u 1 0|) (min |u 0 1 - u 1 1| |u 1 0 - u 1 1|)

end Ito2026Adversarial
end

-- ═══ Ito2026Adversarial.ILMTW2026.Lemma10 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset Real Learning Learning.ZeroSumGame
  Learning.RepeatedGame
universe u
namespace Ito2026Adversarial

/-- **Lemma 10** (Ito, Luo, Maiti, Tsuchiya, Wu 2026). Let `u` be a `2 × 2` zero-sum game with
entries in `[-1, 1]` and without pure-strategy Nash equilibrium. Then `Δ^mix ≥ Δ_M² / 4`, where
`Δ_M = min {|a - b|, |a - c|, |b - d|, |c - d|}` is the minimum entry gap.

The paper assumes a unique mixed-strategy Nash equilibrium, and its proof uses that there is no
PSNE (the lemma is false for a unique pure equilibrium, where `Δ^mix = 0 < Δ_M² / 4` in general).
A `2 × 2` game without PSNE has a unique mixed equilibrium, so uniqueness is not assumed. -/
theorem sq_entryGap_div_four_le_mixGap (u : Fin 2 → Fin 2 → ℝ)
    (hu : ∀ x y, u x y ∈ Set.Icc (-1) 1) (hpure : ¬ HasPSNE u) :
    entryGap u ^ 2 / 4 ≤ mixGap u := sorry

end Ito2026Adversarial
end
