module

public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.MeasureTheory.Order.Lattice
public import Mathlib.Analysis.Convex.Basic
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.Normed.Lp.MeasurableSpace
public import Mathlib.Geometry.Convex.ConvexSpace.CompactSpaceStdSimplex
public import Mathlib.MeasureTheory.Measure.GiryMonad
public import Mathlib.MeasureTheory.Measure.Dirac.Basic
public import Mathlib.MeasureTheory.Measure.Dirac.Def
public import Mathlib.Algebra.BigOperators.Field
public import Mathlib.Probability.IdentDistrib
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Order
public import Mathlib.Analysis.InnerProductSpace.Basic
public import Mathlib.Data.EReal.Basic
public import Mathlib.Analysis.SpecialFunctions.Pow.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.ContinuousLinearMap
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Basic
public import Mathlib.Analysis.Calculus.FDeriv.Measurable
public import Mathlib.Analysis.Calculus.Gradient.Basic
public import Mathlib.Data.Matrix.Mul
public import Mathlib.Order.ConditionallyCompleteLattice.Finset
public import Mathlib.Probability.Kernel.Composition.CompProd
public import Mathlib.Algebra.BigOperators.Intervals
public import Mathlib.Analysis.Calculus.LineDeriv.Basic
public import Mathlib.Analysis.Convex.Function
public import Mathlib.Topology.Algebra.Module.ContinuousLinearMap.PiProd
public import Mathlib.Analysis.SpecialFunctions.Log.Basic
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Inner
public import Mathlib.CategoryTheory.Countable
public import Mathlib.MeasureTheory.Constructions.Polish.Basic
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.Probability.Distributions.Bernoulli
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Analysis.Matrix.MeasurableSpace
public import Mathlib.Analysis.RCLike.Lemmas
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Complex
public import Mathlib.MeasureTheory.Group.Arithmetic
public import Mathlib.Topology.Instances.Matrix
public import Mathlib.LinearAlgebra.Matrix.PosDef
public import Mathlib.Analysis.Matrix.Order
public import Mathlib.Analysis.CStarAlgebra.Matrix
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.Analysis.Convex.Hull
public import Mathlib.LinearAlgebra.Matrix.SchurComplement
public import Mathlib.Analysis.Convex.Caratheodory
public import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
public import Mathlib.Topology.Algebra.Ring.Real
public import Mathlib.Analysis.Convex.Integral
public import Mathlib.Analysis.Convex.SpecificFunctions.Pow
public import Mathlib.NumberTheory.Harmonic.Bounds
public import Mathlib.MeasureTheory.Integral.IntegrableOn
public import Mathlib.Probability.Kernel.Composition.Lemmas
public import Mathlib.Analysis.Convex.SpecificFunctions.Basic
public import Mathlib.Analysis.SpecialFunctions.Pow.Deriv
public import Mathlib.Analysis.Calculus.MeanValue
public import Mathlib.Analysis.MeanInequalitiesPow

/-! # Standalone extraction for `Ito2026Adversarial.exists_psmr_tsallisINFHalf_le`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Real
end Real
namespace Finset
end Finset
namespace Learning
end Learning
namespace Bandits
end Bandits
namespace Bandits.TsallisINF
end Bandits.TsallisINF
namespace Learning.ZeroSumGame
end Learning.ZeroSumGame
namespace Learning.RepeatedGame
end Learning.RepeatedGame
namespace Matrix
end Matrix
namespace Ito2026Adversarial
end Ito2026Adversarial

-- ═══ LeanMachineLearning.SequentialLearning.Algorithm ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- One round of interaction: an observation, then an action, then a feedback. -/
abbrev Round (𝓞 𝓐 𝓨 : Type*) := 𝓞 × 𝓐 × 𝓨

/-- The observation of a round. -/
def Round.obs (r : Round 𝓞 𝓐 𝓨) : 𝓞 := r.1

/-- The action of a round. -/
def Round.action (r : Round 𝓞 𝓐 𝓨) : 𝓐 := r.2.1

/-- The feedback of a round. -/
def Round.feedback (r : Round 𝓞 𝓐 𝓨) : 𝓨 := r.2.2

/-- History of `n` complete rounds; `n = 0` is the empty history. -/
abbrev Hist (𝓞 𝓐 𝓨 : Type*) (n : ℕ) := Fin n → Round 𝓞 𝓐 𝓨

/-- A stochastic, sequential algorithm.
At each round, it sees an observation in `𝓞`, then takes an action in `𝓐`, and finally receives
feedback in `𝓨`. The action is a random function of the past rounds and the current observation. -/
@[ext]
structure Algorithm (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the action of round `n` given the past rounds and the current observation. -/
  policy : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n × 𝓞) 𝓐
  /-- The policy is a Markov kernel. -/
  [isMarkovKernel_policy : ∀ n, IsMarkovKernel (policy n)]

instance instIsMarkovKernelProdHistPolicy (alg : Algorithm 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (alg.policy n) :=
  alg.isMarkovKernel_policy n

/-- A stochastic environment.
At each round, an observation is drawn prior to the algorithm taking an action. Then the environment
provides feedback based on the observation and the action. -/
@[ext]
structure Environment (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the observation of round `n` given the past rounds. -/
  obs : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n) 𝓞
  /-- Law of the feedback of round `n` given the past rounds, the observation and the action. -/
  feedback : (n : ℕ) → Kernel ((Hist 𝓞 𝓐 𝓨 n × 𝓞) × 𝓐) 𝓨
  /-- The observation kernel is a Markov kernel. -/
  [isMarkovKernel_obs : ∀ n, IsMarkovKernel (obs n)]
  /-- The feedback kernel is a Markov kernel. -/
  [isMarkovKernel_feedback : ∀ n, IsMarkovKernel (feedback n)]

section IsAlgEnvSeq
variable {O : ℕ → Ω → 𝓞} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨} {P : Measure Ω} [IsFiniteMeasure P] {N : ℕ}

/-- History of the algorithm-environment sequence before time `n`: the rounds at
times `0, ..., n - 1`. -/
def history (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) : Hist 𝓞 𝓐 𝓨 n :=
  fun i ↦ (O i ω, A i ω, Y i ω)

/-- An algorithm-environment sequence: a sequence of observations, actions and feedbacks generated
by an algorithm interacting with an environment. -/
structure IsAlgEnvSeq
    (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)
    (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨)
    (P : Measure Ω) [IsFiniteMeasure P] : Prop where
  /-- The observation sequence is measurable. -/
  measurable_obs n : Measurable (O n) := by fun_prop
  /-- The action sequence is measurable. -/
  measurable_action n : Measurable (A n) := by fun_prop
  /-- The feedback sequence is measurable. -/
  measurable_feedback n : Measurable (Y n) := by fun_prop
  /-- The observation at time `n` has the correct conditional distribution given the history. -/
  hasCondDistrib_obs n :
    HasCondDistrib (O n) (history O A Y n) (env.obs n) P
  /-- The action at time `n` has the correct conditional distribution given the history and the
  observation at time `n`. -/
  hasCondDistrib_action n :
    HasCondDistrib (A n) (fun ω ↦ (history O A Y n ω, O n ω)) (alg.policy n) P
  /-- The feedback at time `n` has the correct conditional distribution given the history, the
  observation and the action at time `n`. -/
  hasCondDistrib_feedback n :
    HasCondDistrib (Y n) (fun ω ↦ ((history O A Y n ω, O n ω), A n ω)) (env.feedback n) P

end IsAlgEnvSeq
end Learning
end

-- ═══ LeanMachineLearning.SequentialLearning.Comap ═══
@[expose] public section
open MeasureTheory ProbabilityTheory
namespace Learning
variable {𝓞 𝓞' 𝓞'' 𝓐 𝓐' 𝓐'' 𝓨 𝓨' 𝓨'' Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓞' : MeasurableSpace 𝓞'} {m𝓞'' : MeasurableSpace 𝓞''} {m𝓐 : MeasurableSpace 𝓐} {m𝓐' : MeasurableSpace 𝓐'} {m𝓐'' : MeasurableSpace 𝓐''} {m𝓨 : MeasurableSpace 𝓨} {m𝓨' : MeasurableSpace 𝓨'} {m𝓨'' : MeasurableSpace 𝓨''} {mΩ : MeasurableSpace Ω} {fo : 𝓞 → 𝓞'} {fa : 𝓐 → 𝓐'} {fy : 𝓨 → 𝓨'} {go : 𝓞' → 𝓞''} {ga : 𝓐' → 𝓐''} {gy : 𝓨' → 𝓨''}
section Map

/-- Transport a round along maps of the observation, the action and the feedback. -/
def Round.map (fo : 𝓞 → 𝓞') (fa : 𝓐 → 𝓐') (fy : 𝓨 → 𝓨') (r : Round 𝓞 𝓐 𝓨) : Round 𝓞' 𝓐' 𝓨' :=
  (fo r.obs, fa r.action, fy r.feedback)

/-- Transport a history round-wise. -/
def Hist.map (fo : 𝓞 → 𝓞') (fa : 𝓐 → 𝓐') (fy : 𝓨 → 𝓨') {n : ℕ} (h : Hist 𝓞 𝓐 𝓨 n) :
    Hist 𝓞' 𝓐' 𝓨' n :=
  fun i ↦ Round.map fo fa fy (h i)

@[fun_prop]
lemma Hist.measurable_map (hfo : Measurable fo) (hfa : Measurable fa) (hfy : Measurable fy)
    (n : ℕ) :
    Measurable (Hist.map fo fa fy (n := n)) := sorry

/-- Transport the feedback of a history. -/
abbrev Hist.mapFeedback (f : 𝓨 → 𝓨') {n : ℕ} (h : Hist 𝓞 𝓐 𝓨 n) : Hist 𝓞 𝓐 𝓨' n :=
  Hist.map id id f h

end Map
section Comap

/-- The algorithm with observations in `𝓞'` and feedbacks in `𝓨'` obtained from
`alg : Algorithm 𝓞 𝓐 𝓨` by transforming the pair (past rounds, current observation) by `F n` at
each round `n` before applying the policy of `alg`.

This is the primitive transport operation on algorithms: `Algorithm.comapObs` and
`Algorithm.comapFeedback` are the special cases in which `F n` is a round-wise map of the
observation and of the feedback. -/
def Algorithm.comap (alg : Algorithm 𝓞 𝓐 𝓨)
    (F : (n : ℕ) → Hist 𝓞' 𝓐 𝓨' n × 𝓞' → Hist 𝓞 𝓐 𝓨 n × 𝓞) (hF : ∀ n, Measurable (F n)) :
    Algorithm 𝓞' 𝓐 𝓨' where
  policy n := (alg.policy n).comap (F n) (hF n)

section ComapFeedback
variable {g : 𝓨' → 𝓨}

/-- The algorithm that sees `g y` when the feedback of a past round is `y`. -/
def Algorithm.comapFeedback (alg : Algorithm 𝓞 𝓐 𝓨) (g : 𝓨' → 𝓨)
    (hg : Measurable g := by fun_prop) : Algorithm 𝓞 𝓐 𝓨' :=
  alg.comap (fun _ p ↦ (Hist.mapFeedback g p.1, p.2)) fun _ ↦ by fun_prop

end ComapFeedback
end Comap
end Learning
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.SequentialLearning.Algorithms.Stateful ═══
@[expose] public section
open MeasureTheory ProbabilityTheory
namespace Learning
variable {𝓞 𝓐 𝓨 𝓞' 𝓐' 𝓨' σ Ω : Type*}

/-- The state after the `t` rounds of history `h`, starting from `s0` and updating at round `t`
by `upd t`. -/
def foldHistIdx (upd : ℕ → σ → Round 𝓞 𝓐 𝓨 → σ) (s0 : σ) : (t : ℕ) → Hist 𝓞 𝓐 𝓨 t → σ
  | 0, _ => s0
  | t + 1, h => upd t (foldHistIdx upd s0 t fun i ↦ h i.castSucc) (h (Fin.last t))

variable [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] [MeasurableSpace σ]

@[fun_prop]
lemma measurable_foldHistIdx {upd : ℕ → σ → Round 𝓞 𝓐 𝓨 → σ}
    (hupd : Measurable fun p : ℕ × σ × Round 𝓞 𝓐 𝓨 ↦ upd p.1 p.2.1 p.2.2) (s0 : σ) (t : ℕ) :
    Measurable (foldHistIdx upd s0 t) := sorry

/-- The stateful algorithm with initial state `s0`, state update `upd` and policy `π`: the action
at round `n` is drawn from `π n` applied to the current state and the current observation. -/
noncomputable def Algorithm.stateful (s0 : σ) (upd : ℕ → σ → Round 𝓞 𝓐 𝓨 → σ)
    (hupd : Measurable fun p : ℕ × σ × Round 𝓞 𝓐 𝓨 ↦ upd p.1 p.2.1 p.2.2)
    (π : ℕ → Kernel (σ × 𝓞) 𝓐) [∀ n, IsMarkovKernel (π n)] : Algorithm 𝓞 𝓐 𝓨 where
  policy n := (π n).comap (fun p ↦ (foldHistIdx upd s0 n p.1, p.2))
    (((measurable_foldHistIdx hupd s0 n).comp measurable_fst).prodMk measurable_snd)

variable [MeasurableSpace Ω]
end Learning
end

-- ═══ LeanMachineLearning.ForMathlib.MeasureTheory.Order.Lattice ═══
@[expose] public section
open Finset
variable {α δ : Type*} [MeasurableSpace δ] [SemilatticeInf α] {m : MeasurableSpace α} [MeasurableInf₂ α]
attribute [to_dual existing] MeasurableInf₂
end

-- ═══ Ito2026Adversarial.Mathlib.Analysis.Convex.Simplex ═══
@[expose] public section
open MeasureTheory
namespace Learning
variable {ι : Type*} [Fintype ι]

/-- The probability simplex `{p | ∀ i, 0 ≤ p i, ∑ i, p i = 1}` of `EuclideanSpace ℝ ι`. -/
def simplex (ι : Type*) [Fintype ι] : Set (EuclideanSpace ℝ ι) :=
  {p | (∀ i, 0 ≤ p i) ∧ ∑ i, p i = 1}

/-- A point of the simplex is a function on `ι`: `p i` is its `i`-th coordinate. -/
instance instCoeFunElemEuclideanSpaceRealSimplexForall : CoeFun (simplex ι) (fun _ ↦ ι → ℝ) := ⟨fun p ↦ (p : EuclideanSpace ℝ ι).ofLp⟩

@[fun_prop]
lemma measurable_coe_simplex : Measurable fun p : simplex ι ↦ (p : ι → ℝ) := sorry

/-- The uniform distribution `(1/|ι|, …, 1/|ι|)` of `EuclideanSpace ℝ ι`. -/
noncomputable def uniformVec (ι : Type*) [Fintype ι] : EuclideanSpace ℝ ι :=
  (EuclideanSpace.equiv ι ℝ).symm fun _ ↦ (Fintype.card ι : ℝ)⁻¹

lemma uniformVec_mem_simplex [Nonempty ι] : uniformVec ι ∈ simplex ι := sorry

/-- The uniform distribution, as an element of the simplex. -/
noncomputable def uniformSimplex (ι : Type*) [Fintype ι] [Nonempty ι] : simplex ι :=
  ⟨uniformVec ι, uniformVec_mem_simplex⟩

instance instNonemptyElemEuclideanSpaceRealSimplex [Nonempty ι] : Nonempty (simplex ι) := ⟨uniformSimplex ι⟩

end Learning
end

-- ═══ Ito2026Adversarial.Mathlib.MeasureTheory.Measure.Weighted ═══
@[expose] public section
open scoped ENNReal
namespace MeasureTheory
variable {ι : Type*} [Fintype ι] [MeasurableSpace ι] {p q : ι → ℝ}

/-- The measure on `ι` with weights `p`: `∑ i, p i • δ_i` (negative weights count as `0`). -/
noncomputable def weightedMeasure (p : ι → ℝ) : Measure ι :=
  ∑ i, ENNReal.ofReal (p i) • Measure.dirac i

/-- The weighted measure of a probability vector is a probability measure. -/
lemma isProbabilityMeasure_weightedMeasure (hp0 : ∀ i, 0 ≤ p i) (hp1 : ∑ i, p i = 1) :
    IsProbabilityMeasure (weightedMeasure p) := sorry

/-- The map `p ↦ weightedMeasure p` is measurable. -/
lemma measurable_weightedMeasure : Measurable (weightedMeasure (ι := ι)) := sorry

end MeasureTheory
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Online.Bandit.ImportanceWeighting ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset
namespace Learning
variable {ι : Type*} [Fintype ι] [MeasurableSpace ι]

/-- The kernel sampling an index `i ∼ p` from a point `p` of the simplex. -/
noncomputable def simplexKernel (ι : Type*) [Fintype ι] [MeasurableSpace ι] :
    Kernel (simplex ι) ι where
  toFun p := weightedMeasure p
  measurable' := measurable_weightedMeasure.comp (by fun_prop)

instance instIsMarkovKernelElemEuclideanSpaceRealSimplexSimplexKernel : IsMarkovKernel (simplexKernel ι) :=
  ⟨fun p ↦ isProbabilityMeasure_weightedMeasure p.2.1 p.2.2⟩

end Learning
namespace Bandits
variable {ι : Type*} [DecidableEq ι]

/-- The importance-weighted estimate of a loss vector, from the loss `v` of the arm `i` drawn
with probability `p i`: `v / p i` at `i` and `0` elsewhere. -/
noncomputable def importanceWeighted (p : ι → ℝ) (i : ι) (v : ℝ) (j : ι) : ℝ :=
  if i = j then v / p i else 0

end Bandits
end

-- ═══ Ito2026Adversarial.Mathlib.MeasureTheory.MeasurableSpace.ToSet ═══
@[expose] public section
namespace Learning
variable {X : Type*} {K : Set X} [Nonempty K] {v : X}

open scoped Classical in
/-- The point `v` as an element of `K`, or an arbitrary element of `K` if `v ∉ K`. -/
noncomputable def toSet (K : Set X) [Nonempty K] (v : X) : K :=
  if h : v ∈ K then ⟨v, h⟩ else Classical.arbitrary K

end Learning
end

-- ═══ Ito2026Adversarial.Mathlib.Analysis.Convex.FenchelConjugate ═══
@[expose] public section
open scoped RealInnerProductSpace
variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] {s t : Set E} {f : E → ℝ} {x θ : E}

/-- The Fenchel conjugate of `f` restricted to `s`: `θ ↦ sup_{x ∈ s} ⟪x, θ⟫ - f x`, with values in
`EReal` (`⊥` if `s` is empty, `⊤` if the supremum is infinite). -/
noncomputable def fenchelConjugateOn (s : Set E) (f : E → ℝ) (θ : E) : EReal :=
  ⨆ x : s, ((⟪(x : E), θ⟫ - f x : ℝ) : EReal)

end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Online.Bandit.SimplexFTRL ═══
@[expose] public section
open MeasureTheory Finset
open scoped RealInnerProductSpace
namespace Learning
variable {ι : Type*} [Fintype ι]

/-- The value function `Φ(θ) = sup_{p ∈ simplex} ⟪p, θ⟫ + φ p` of FTRL with regularizer `φ`: the
Fenchel conjugate of `-φ` on the simplex. -/
noncomputable def ftrlValue (φ : EuclideanSpace ℝ ι → ℝ) (θ : EuclideanSpace ℝ ι) : ℝ :=
  (fenchelConjugateOn (simplex ι) (-φ) θ).toReal

/-- The FTRL distribution `argmax_{p ∈ simplex} ⟪p, θ⟫ + φ p`, defined as the gradient of the
value function `ftrlValue φ` at `θ` (an arbitrary element of the simplex where the value function
is not differentiable). -/
noncomputable def ftrlSimplex [Nonempty ι] (φ : EuclideanSpace ℝ ι → ℝ) (θ : EuclideanSpace ℝ ι) :
    simplex ι :=
  toSet (simplex ι) (gradient (ftrlValue φ) θ)

/-- The Tsallis entropy `φ_α(p) = (1 / α) ∑ i, (p i ^ α - p i)`, nonnegative and concave on the
simplex for `α ∈ (0, 1)`. -/
noncomputable def tsallisEntropy (α : ℝ) (p : EuclideanSpace ℝ ι) : ℝ :=
  α⁻¹ * ∑ i, (p i ^ α - p i)

end Learning
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Online.Bandit.TsallisINF ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset Learning
open scoped RealInnerProductSpace
namespace Bandits
variable {ι : Type*} [Fintype ι] [DecidableEq ι] [MeasurableSpace ι] [MeasurableSingletonClass ι]
namespace TsallisINF

/-- The importance-weighted reward estimate of a round played with the distribution `p`:
`g x = 1 - (1 - r) / p x` for the arm `x` played, with reward `r`, and `g x = 1` otherwise (the
importance-weighted estimate `importanceWeighted p x (1 - r)` of the loss vector `1 - g`). -/
noncomputable def estimate (p : simplex ι) (r : Round Unit ι ℝ) : EuclideanSpace ℝ ι :=
  WithLp.toLp _ (1 - importanceWeighted (fun x ↦ (p : EuclideanSpace ℝ ι) x) r.action
    (1 - r.feedback))

variable [Nonempty ι]

/-- The distribution played at round `n` from the cumulative estimate `G`:
`argmax_{p ∈ simplex} ⟪p, G⟫ + φ_α(p) / η n = argmax_{p ∈ simplex} ⟪p, η n • G⟫ + φ_α(p)`. -/
noncomputable def dist (α : ℝ) (η : ℕ → ℝ) (n : ℕ) (G : EuclideanSpace ℝ ι) : simplex ι :=
  ftrlSimplex (tsallisEntropy α) (η n • G)

omit [DecidableEq ι] [MeasurableSpace ι] [MeasurableSingletonClass ι] in
@[fun_prop]
lemma measurable_dist {X : Type*} [MeasurableSpace X] (α : ℝ) (η : ℕ → ℝ) {n : X → ℕ}
    {G : X → EuclideanSpace ℝ ι} (hn : Measurable n) (hG : Measurable G) :
    Measurable fun x ↦ dist α η (n x) (G x) := sorry

/-- The state update of Tsallis-INF at round `n`: `G ↦ G + g_n`. -/
noncomputable def update (α : ℝ) (η : ℕ → ℝ) (n : ℕ) (G : EuclideanSpace ℝ ι)
    (r : Round Unit ι ℝ) : EuclideanSpace ℝ ι :=
  G + estimate (dist α η n G) r

@[fun_prop]
lemma measurable_update {X : Type*} [MeasurableSpace X] (α : ℝ) (η : ℕ → ℝ) {n : X → ℕ}
    {G : X → EuclideanSpace ℝ ι} {r : X → Round Unit ι ℝ} (hn : Measurable n) (hG : Measurable G)
    (hr : Measurable r) : Measurable fun x ↦ update α η (n x) (G x) (r x) := sorry

/-- The policy of Tsallis-INF at round `n` from the state `G_n`: sample from `dist α η n G_n`. -/
noncomputable def policy (α : ℝ) (η : ℕ → ℝ) (n : ℕ) : Kernel (EuclideanSpace ℝ ι × Unit) ι :=
  (simplexKernel ι).comap (fun q ↦ dist α η n q.1) (by fun_prop)

instance instIsMarkovKernelProdEuclideanSpaceRealUnitPolicy (α : ℝ) (η : ℕ → ℝ) (n : ℕ) : IsMarkovKernel (policy (ι := ι) α η n) := by
  unfold policy; infer_instance

end TsallisINF
variable [Nonempty ι]

/-- **Tsallis-INF** with entropy parameter `α` and learning rates `η`: at round `n`, play an arm
drawn from `argmax_{p ∈ simplex} ⟪p, G_n⟫ + φ_α(p) / η n`, where `G_n` is the cumulative
importance-weighted reward estimate. -/
noncomputable def tsallisINF (α : ℝ) (η : ℕ → ℝ) : Algorithm Unit ι ℝ :=
  Algorithm.stateful 0 (TsallisINF.update α η) (by fun_prop) (TsallisINF.policy α η)

end Bandits
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Game.ZeroSum ═══
@[expose] public section
open Finset
namespace Learning.ZeroSumGame
variable {𝒳 𝒴 : Type*} {u : 𝒳 → 𝒴 → ℝ} {x : 𝒳} {y : 𝒴}

/-- `(x, y)` is a strict pure-strategy Nash equilibrium of `u`: `u x' y < u x y < u x y'` for all
`x' ≠ x`, `y' ≠ y`. -/
def IsStrictPSNE (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) : Prop :=
  (∀ x' ≠ x, u x' y < u x y) ∧ ∀ y' ≠ y, u x y < u x y'

/-- The pure-strategy maximin value `v* = max_x min_y u x y`. -/
noncomputable def pureMaximin (u : 𝒳 → 𝒴 → ℝ) : ℝ := ⨆ x, ⨅ y, u x y

/-- The sub-optimality gap `Δʳ_{x'} = u x y - u x' y` of the row action `x'` at the equilibrium
`(x, y)`. -/
def rowGap (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) (x' : 𝒳) : ℝ := u x y - u x' y

/-- The sub-optimality gap `Δᶜ_{y'} = u x y' - u x y` of the column action `y'` at the
equilibrium `(x, y)`. -/
def colGap (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) (y' : 𝒴) : ℝ := u x y' - u x y

/-- The minimal column gap `Δᶜ_min = min_{y' ≠ y} Δᶜ_{y'}`. -/
noncomputable def colGapMin (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) : ℝ :=
  ⨅ y' : {y' // y' ≠ y}, colGap u x y y'

section Mixed
variable [Fintype 𝒳] [Fintype 𝒴]

/-- The expected utility `∑ x y, p x * q y * u x y` of the mixed strategies `p` and `q`. -/
def mixedUtility (u : 𝒳 → 𝒴 → ℝ) (p : EuclideanSpace ℝ 𝒳) (q : EuclideanSpace ℝ 𝒴) : ℝ :=
  ∑ x, ∑ y, p x * q y * u x y

/-- The mixed-strategy maximin value `max_p min_q u(p, q)`, which is the value `v^Nash` of the
Nash equilibria of the game (von Neumann's minimax theorem). -/
noncomputable def nashValue (u : 𝒳 → 𝒴 → ℝ) : ℝ :=
  ⨆ p : simplex 𝒳, ⨅ q : simplex 𝒴, mixedUtility u p q

/-- The gap `Δ^mix = v^Nash - v*` between the Nash value and the pure-strategy maximin value. -/
noncomputable def mixGap (u : 𝒳 → 𝒴 → ℝ) : ℝ := nashValue u - pureMaximin u

end Mixed
end Learning.ZeroSumGame
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Game.RepeatedGame ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset
open scoped ProbabilityTheory
namespace Learning.RepeatedGame
open ZeroSumGame
variable {𝒳 𝒴 : Type*} [MeasurableSpace 𝒳] [MeasurableSpace 𝒴]

/-- A player of the repeated game with actions `𝒳`, against an opponent with actions `𝒴`: an
algorithm that observes, after each round, the opponent's action and the reward. -/
abbrev Player (𝒳 𝒴 : Type*) [MeasurableSpace 𝒳] [MeasurableSpace 𝒴] :=
  Algorithm Unit 𝒳 (𝒴 × ℝ)

/-- A round `(x, (y, r))` seen from the opponent: `(y, (x, r))`. -/
def Round.swapPlayers (r : Round Unit 𝒳 (𝒴 × ℝ)) : Round Unit 𝒴 (𝒳 × ℝ) :=
  ((), r.feedback.1, (r.action, r.feedback.2))

/-- A history seen from the opponent. -/
def Hist.swapPlayers {n : ℕ} (h : Hist Unit 𝒳 (𝒴 × ℝ) n) : Hist Unit 𝒴 (𝒳 × ℝ) n :=
  fun i ↦ Round.swapPlayers (h i)

@[fun_prop]
lemma Hist.measurable_swapPlayers (n : ℕ) :
    Measurable (Hist.swapPlayers (𝒳 := 𝒳) (𝒴 := 𝒴) (n := n)) := sorry

/-- A reward kernel: the law of the reward of a round given the past rounds and the two actions
of the round. -/
abbrev RewardKernel (𝒳 𝒴 : Type*) [MeasurableSpace 𝒳] [MeasurableSpace 𝒴] :=
  (n : ℕ) → Kernel (Hist Unit 𝒳 (𝒴 × ℝ) n × 𝒳 × 𝒴) ℝ

/-- The reward kernel has conditional mean `u x y`: the noise `r_t - u x_t y_t` is a martingale
difference sequence. -/
def RewardKernel.HasMean (R : RewardKernel 𝒳 𝒴) (u : 𝒳 → 𝒴 → ℝ) : Prop :=
  ∀ n (h : Hist Unit 𝒳 (𝒴 × ℝ) n) x y, ∫ r, r ∂(R n (h, x, y)) = u x y

/-- The rewards lie in the set `s` almost surely. -/
def RewardKernel.RewardsIn (R : RewardKernel 𝒳 𝒴) (s : Set ℝ) : Prop :=
  ∀ n (h : Hist Unit 𝒳 (𝒴 × ℝ) n) x y, ∀ᵐ r ∂(R n (h, x, y)), r ∈ s

/-- The environment of the learner playing against the opponent `opp` with reward kernel `R`: the
feedback of a round is `(y, r)` with `y` drawn from the policy of `opp` on the past rounds (seen
from the opponent) and `r` from `R`. -/
noncomputable def gameEnv (opp : Player 𝒴 𝒳) (R : RewardKernel 𝒳 𝒴) [∀ n, IsMarkovKernel (R n)] :
    Environment Unit 𝒳 (𝒴 × ℝ) where
  obs _ := Kernel.const _ (Measure.dirac ())
  feedback n :=
    ((opp.policy n).comap
      (fun p : (Hist Unit 𝒳 (𝒴 × ℝ) n × Unit) × 𝒳 ↦ (Hist.swapPlayers p.1.1, ())) (by fun_prop))
    ⊗ₖ ((R n).comap (fun q : ((Hist Unit 𝒳 (𝒴 × ℝ) n × Unit) × 𝒳) × 𝒴 ↦ (q.1.1.1, q.1.2, q.2))
      (by fun_prop))

/-- An uninformed learner, which observes only the rewards, as a player of the repeated game
(ignoring the opponent's actions in the feedback). -/
noncomputable def Player.ofUninformed (alg : Algorithm Unit 𝒳 ℝ) : Player 𝒳 𝒴 :=
  alg.comapFeedback Prod.snd measurable_snd

section Regret
omit [MeasurableSpace 𝒳] [MeasurableSpace 𝒴]
variable {Ω : Type*} {mΩ : MeasurableSpace Ω}

/-- The pure-strategy maximin regret `PSMR_T = E[∑_{t<T} (v* - u x_t y_t)]` of the run `(X, Y)`
under `P`. -/
noncomputable def psmr (u : 𝒳 → 𝒴 → ℝ) (X : ℕ → Ω → 𝒳) (Y : ℕ → Ω → 𝒴) (P : Measure Ω)
    (T : ℕ) : ℝ :=
  P[fun ω ↦ ∑ t ∈ range T, (pureMaximin u - u (X t ω) (Y t ω))]

end Regret
end Learning.RepeatedGame
end

-- ═══ Ito2026Adversarial.ILMTW2026.Setting ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset Learning Learning.ZeroSumGame Learning.RepeatedGame
  Matrix Real
open scoped RealInnerProductSpace
namespace Ito2026Adversarial

/-- Tsallis-INF with `α = 1/2` and `η_t = 1 / (2 √t)` (Theorem 1), on the arms `Fin mx`. -/
noncomputable def tsallisINFHalf (mx : ℕ) [NeZero mx] : Algorithm Unit (Fin mx) ℝ :=
  Bandits.tsallisINF (1 / (2 : ℕ)) fun n ↦ 1 / ((2 : ℕ) * √(n + 1))

end Ito2026Adversarial
end

-- ═══ Ito2026Adversarial.ILMTW2026.Theorem1 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset Real Learning Learning.ZeroSumGame
  Learning.RepeatedGame
universe u
namespace Ito2026Adversarial

/-- **Theorem 1** (Ito, Luo, Maiti, Tsuchiya, Wu 2026). There is a universal constant `C` such
that for every game `u` with utilities in `[-1, 1]`, every adaptive adversary and every reward
noise with conditional mean `u` and rewards in `[-1, 1]`, the run of Tsallis-INF (`α = 1/2`,
`η_t = 1 / (2 √t)`) satisfies `PSMR_T ≤ C √(m_x T)`; moreover
`PSMR_T ≤ C (1 + 1 / Δᶜ_min) ∑_{x ≠ x*} (1 + log T) / Δʳ_x` if `(x*, y*)` is a strict PSNE and
`PSMR_T ≤ C m_x / Δ^mix` if `Δ^mix > 0`.

The paper states the second bound as `O((1 / Δᶜ_min) ∑_{x ≠ x*} log T / Δʳ_x)`; the form above is
the one its proof gives, and implies the paper's for `m_y ≥ 2` and `T ≥ 2` (`Δᶜ_min ≤ 2`). For
`m_y = 1` the paper's form is false in Lean, where `Δᶜ_min` is an infimum over no action and
`C / 0 = 0`. The paper states the third bound for games without PSNE, claiming that they have
`Δ^mix > 0`; this fails in general (the rows `(0, 0)`, `(1, -1)`, `(-1, 1)` give a game without
PSNE with `v* = v^Nash = 0`), and the proof only uses `Δ^mix > 0`. -/
theorem exists_psmr_tsallisINFHalf_le :
    ∃ C : ℝ, 0 < C ∧ ∀ {mx my : ℕ} [NeZero mx] [NeZero my] (u : Fin mx → Fin my → ℝ),
      (∀ x y, u x y ∈ Set.Icc (-1) 1) →
      ∀ (opp : Player (Fin my) (Fin mx)) (R : RewardKernel (Fin mx) (Fin my))
        [∀ n, IsMarkovKernel (R n)],
      RewardKernel.HasMean R u → RewardKernel.RewardsIn R (Set.Icc (-1) 1) →
      ∀ {Ω : Type u} {_mΩ : MeasurableSpace Ω} (P : Measure Ω) [IsProbabilityMeasure P]
        (X : ℕ → Ω → Fin mx) (Y : ℕ → Ω → Fin my) (Rw : ℕ → Ω → ℝ),
      IsAlgEnvSeq (fun _ _ ↦ ()) X (fun t ω ↦ (Y t ω, Rw t ω))
        (Player.ofUninformed (tsallisINFHalf mx)) (gameEnv opp R) P →
      ∀ T : ℕ,
        psmr u X Y P T ≤ C * √(mx * T) ∧
        (∀ x₀ y₀, IsStrictPSNE u x₀ y₀ →
          psmr u X Y P T ≤
            C * (1 + 1 / colGapMin u x₀ y₀) *
              ∑ x ∈ univ.erase x₀, (1 + log T) / rowGap u x₀ y₀ x) ∧
        (0 < mixGap u → psmr u X Y P T ≤ C * mx / mixGap u) := sorry

end Ito2026Adversarial
end
