module

public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.MeasureTheory.Order.Lattice
public import Mathlib.Data.Matrix.Mul
public import Mathlib.Order.ConditionallyCompleteLattice.Finset
public import Mathlib.Analysis.Convex.Basic
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.Normed.Lp.MeasurableSpace
public import Mathlib.Geometry.Convex.ConvexSpace.CompactSpaceStdSimplex
public import Mathlib.Probability.Kernel.Composition.CompProd
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Algebra.BigOperators.Intervals
public import Mathlib.Analysis.Calculus.Gradient.Basic
public import Mathlib.Analysis.Calculus.LineDeriv.Basic
public import Mathlib.Analysis.Convex.Function
public import Mathlib.Topology.Algebra.Module.ContinuousLinearMap.PiProd
public import Mathlib.Analysis.Complex.ExponentialBounds
public import Mathlib.InformationTheory.KullbackLeibler.Basic
public import Mathlib.MeasureTheory.Integral.Indicator
public import Mathlib.Probability.Martingale.Convergence
public import Mathlib.InformationTheory.KullbackLeibler.DataProcessing
public import Mathlib.MeasureTheory.Function.ConditionalExpectation.RadonNikodym
public import Mathlib.InformationTheory.KullbackLeibler.ChainRule
public import Mathlib.Probability.Kernel.Composition.RadonNikodym
public import Mathlib.Probability.Kernel.Composition.AbsolutelyContinuous
public import Mathlib.Probability.Kernel.Composition.Lemmas
public import Mathlib.Probability.Distributions.Bernoulli
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Analysis.Calculus.Deriv.MeanValue
public import Mathlib.Analysis.SpecialFunctions.BinaryEntropy
public import Mathlib.Analysis.SpecialFunctions.Log.Deriv
public import Mathlib.MeasureTheory.Measure.Decomposition.Lebesgue
public import Mathlib.MeasureTheory.Integral.Lebesgue.Countable
public import Mathlib.Analysis.SpecialFunctions.Log.Basic
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Inner
public import Mathlib.CategoryTheory.Countable
public import Mathlib.MeasureTheory.Constructions.Polish.Basic
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.Analysis.Matrix.MeasurableSpace
public import Mathlib.Analysis.RCLike.Lemmas
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Complex
public import Mathlib.MeasureTheory.Group.Arithmetic
public import Mathlib.Topology.Instances.Matrix
public import Mathlib.LinearAlgebra.Matrix.PosDef
public import Mathlib.Analysis.Matrix.Order
public import Mathlib.Analysis.CStarAlgebra.Matrix
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.Analysis.Convex.Hull
public import Mathlib.LinearAlgebra.Matrix.SchurComplement
public import Mathlib.Analysis.Convex.Caratheodory
public import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
public import Mathlib.Topology.Algebra.Ring.Real
public import Mathlib.Analysis.SpecialFunctions.Pow.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.ContinuousLinearMap
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Basic
public import Mathlib.Analysis.InnerProductSpace.Basic
public import Mathlib.Data.EReal.Basic
public import Mathlib.Analysis.Calculus.FDeriv.Measurable
public import Mathlib.Algebra.BigOperators.Field
public import Mathlib.Probability.IdentDistrib
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.MeasureTheory.Measure.GiryMonad
public import Mathlib.MeasureTheory.Measure.Dirac.Basic
public import Mathlib.MeasureTheory.Measure.Dirac.Def
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Order

/-! # Standalone extraction for `Ito2026Adversarial.exists_forall_psmr_ge`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Real
end Real
namespace Finset
end Finset
namespace Learning
end Learning
namespace Learning.ZeroSumGame
end Learning.ZeroSumGame
namespace Learning.RepeatedGame
end Learning.RepeatedGame
namespace Ito2026Adversarial
end Ito2026Adversarial

-- ═══ LeanMachineLearning.SequentialLearning.Algorithm ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- One round of interaction: an observation, then an action, then a feedback. -/
abbrev Round (𝓞 𝓐 𝓨 : Type*) := 𝓞 × 𝓐 × 𝓨

/-- The observation of a round. -/
def Round.obs (r : Round 𝓞 𝓐 𝓨) : 𝓞 := r.1

/-- The action of a round. -/
def Round.action (r : Round 𝓞 𝓐 𝓨) : 𝓐 := r.2.1

/-- The feedback of a round. -/
def Round.feedback (r : Round 𝓞 𝓐 𝓨) : 𝓨 := r.2.2

/-- History of `n` complete rounds; `n = 0` is the empty history. -/
abbrev Hist (𝓞 𝓐 𝓨 : Type*) (n : ℕ) := Fin n → Round 𝓞 𝓐 𝓨

/-- A stochastic, sequential algorithm.
At each round, it sees an observation in `𝓞`, then takes an action in `𝓐`, and finally receives
feedback in `𝓨`. The action is a random function of the past rounds and the current observation. -/
@[ext]
structure Algorithm (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the action of round `n` given the past rounds and the current observation. -/
  policy : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n × 𝓞) 𝓐
  /-- The policy is a Markov kernel. -/
  [isMarkovKernel_policy : ∀ n, IsMarkovKernel (policy n)]

instance instIsMarkovKernelProdHistPolicy (alg : Algorithm 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (alg.policy n) :=
  alg.isMarkovKernel_policy n

/-- A stochastic environment.
At each round, an observation is drawn prior to the algorithm taking an action. Then the environment
provides feedback based on the observation and the action. -/
@[ext]
structure Environment (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the observation of round `n` given the past rounds. -/
  obs : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n) 𝓞
  /-- Law of the feedback of round `n` given the past rounds, the observation and the action. -/
  feedback : (n : ℕ) → Kernel ((Hist 𝓞 𝓐 𝓨 n × 𝓞) × 𝓐) 𝓨
  /-- The observation kernel is a Markov kernel. -/
  [isMarkovKernel_obs : ∀ n, IsMarkovKernel (obs n)]
  /-- The feedback kernel is a Markov kernel. -/
  [isMarkovKernel_feedback : ∀ n, IsMarkovKernel (feedback n)]

section IsAlgEnvSeq
variable {O : ℕ → Ω → 𝓞} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨} {P : Measure Ω} [IsFiniteMeasure P] {N : ℕ}

/-- History of the algorithm-environment sequence before time `n`: the rounds at
times `0, ..., n - 1`. -/
def history (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) : Hist 𝓞 𝓐 𝓨 n :=
  fun i ↦ (O i ω, A i ω, Y i ω)

/-- An algorithm-environment sequence: a sequence of observations, actions and feedbacks generated
by an algorithm interacting with an environment. -/
structure IsAlgEnvSeq
    (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)
    (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨)
    (P : Measure Ω) [IsFiniteMeasure P] : Prop where
  /-- The observation sequence is measurable. -/
  measurable_obs n : Measurable (O n) := by fun_prop
  /-- The action sequence is measurable. -/
  measurable_action n : Measurable (A n) := by fun_prop
  /-- The feedback sequence is measurable. -/
  measurable_feedback n : Measurable (Y n) := by fun_prop
  /-- The observation at time `n` has the correct conditional distribution given the history. -/
  hasCondDistrib_obs n :
    HasCondDistrib (O n) (history O A Y n) (env.obs n) P
  /-- The action at time `n` has the correct conditional distribution given the history and the
  observation at time `n`. -/
  hasCondDistrib_action n :
    HasCondDistrib (A n) (fun ω ↦ (history O A Y n ω, O n ω)) (alg.policy n) P
  /-- The feedback at time `n` has the correct conditional distribution given the history, the
  observation and the action at time `n`. -/
  hasCondDistrib_feedback n :
    HasCondDistrib (Y n) (fun ω ↦ ((history O A Y n ω, O n ω), A n ω)) (env.feedback n) P

end IsAlgEnvSeq
end Learning
end

-- ═══ LeanMachineLearning.SequentialLearning.Comap ═══
@[expose] public section
open MeasureTheory ProbabilityTheory
namespace Learning
variable {𝓞 𝓞' 𝓞'' 𝓐 𝓐' 𝓐'' 𝓨 𝓨' 𝓨'' Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓞' : MeasurableSpace 𝓞'} {m𝓞'' : MeasurableSpace 𝓞''} {m𝓐 : MeasurableSpace 𝓐} {m𝓐' : MeasurableSpace 𝓐'} {m𝓐'' : MeasurableSpace 𝓐''} {m𝓨 : MeasurableSpace 𝓨} {m𝓨' : MeasurableSpace 𝓨'} {m𝓨'' : MeasurableSpace 𝓨''} {mΩ : MeasurableSpace Ω} {fo : 𝓞 → 𝓞'} {fa : 𝓐 → 𝓐'} {fy : 𝓨 → 𝓨'} {go : 𝓞' → 𝓞''} {ga : 𝓐' → 𝓐''} {gy : 𝓨' → 𝓨''}
section Map

/-- Transport a round along maps of the observation, the action and the feedback. -/
def Round.map (fo : 𝓞 → 𝓞') (fa : 𝓐 → 𝓐') (fy : 𝓨 → 𝓨') (r : Round 𝓞 𝓐 𝓨) : Round 𝓞' 𝓐' 𝓨' :=
  (fo r.obs, fa r.action, fy r.feedback)

/-- Transport a history round-wise. -/
def Hist.map (fo : 𝓞 → 𝓞') (fa : 𝓐 → 𝓐') (fy : 𝓨 → 𝓨') {n : ℕ} (h : Hist 𝓞 𝓐 𝓨 n) :
    Hist 𝓞' 𝓐' 𝓨' n :=
  fun i ↦ Round.map fo fa fy (h i)

@[fun_prop]
lemma Hist.measurable_map (hfo : Measurable fo) (hfa : Measurable fa) (hfy : Measurable fy)
    (n : ℕ) :
    Measurable (Hist.map fo fa fy (n := n)) := sorry

/-- Transport the feedback of a history. -/
abbrev Hist.mapFeedback (f : 𝓨 → 𝓨') {n : ℕ} (h : Hist 𝓞 𝓐 𝓨 n) : Hist 𝓞 𝓐 𝓨' n :=
  Hist.map id id f h

end Map
section Comap

/-- The algorithm with observations in `𝓞'` and feedbacks in `𝓨'` obtained from
`alg : Algorithm 𝓞 𝓐 𝓨` by transforming the pair (past rounds, current observation) by `F n` at
each round `n` before applying the policy of `alg`.

This is the primitive transport operation on algorithms: `Algorithm.comapObs` and
`Algorithm.comapFeedback` are the special cases in which `F n` is a round-wise map of the
observation and of the feedback. -/
def Algorithm.comap (alg : Algorithm 𝓞 𝓐 𝓨)
    (F : (n : ℕ) → Hist 𝓞' 𝓐 𝓨' n × 𝓞' → Hist 𝓞 𝓐 𝓨 n × 𝓞) (hF : ∀ n, Measurable (F n)) :
    Algorithm 𝓞' 𝓐 𝓨' where
  policy n := (alg.policy n).comap (F n) (hF n)

section ComapFeedback
variable {g : 𝓨' → 𝓨}

/-- The algorithm that sees `g y` when the feedback of a past round is `y`. -/
def Algorithm.comapFeedback (alg : Algorithm 𝓞 𝓐 𝓨) (g : 𝓨' → 𝓨)
    (hg : Measurable g := by fun_prop) : Algorithm 𝓞 𝓐 𝓨' :=
  alg.comap (fun _ p ↦ (Hist.mapFeedback g p.1, p.2)) fun _ ↦ by fun_prop

end ComapFeedback
end Comap
end Learning
end

-- ═══ LeanMachineLearning.ForMathlib.MeasureTheory.Order.Lattice ═══
@[expose] public section
open Finset
variable {α δ : Type*} [MeasurableSpace δ] [SemilatticeInf α] {m : MeasurableSpace α} [MeasurableInf₂ α]
attribute [to_dual existing] MeasurableInf₂
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Game.ZeroSum ═══
@[expose] public section
open Finset
namespace Learning.ZeroSumGame
variable {𝒳 𝒴 : Type*} {u : 𝒳 → 𝒴 → ℝ} {x : 𝒳} {y : 𝒴}

/-- `(x, y)` is a strict pure-strategy Nash equilibrium of `u`: `u x' y < u x y < u x y'` for all
`x' ≠ x`, `y' ≠ y`. -/
def IsStrictPSNE (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) : Prop :=
  (∀ x' ≠ x, u x' y < u x y) ∧ ∀ y' ≠ y, u x y < u x y'

/-- The pure-strategy maximin value `v* = max_x min_y u x y`. -/
noncomputable def pureMaximin (u : 𝒳 → 𝒴 → ℝ) : ℝ := ⨆ x, ⨅ y, u x y

/-- The sub-optimality gap `Δʳ_{x'} = u x y - u x' y` of the row action `x'` at the equilibrium
`(x, y)`. -/
def rowGap (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) (x' : 𝒳) : ℝ := u x y - u x' y

/-- The sub-optimality gap `Δᶜ_{y'} = u x y' - u x y` of the column action `y'` at the
equilibrium `(x, y)`. -/
def colGap (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) (y' : 𝒴) : ℝ := u x y' - u x y

/-- The minimal row gap `Δʳ_min = min_{x' ≠ x} Δʳ_{x'}`. -/
noncomputable def rowGapMin (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) : ℝ :=
  ⨅ x' : {x' // x' ≠ x}, rowGap u x y x'

/-- The minimal column gap `Δᶜ_min = min_{y' ≠ y} Δᶜ_{y'}`. -/
noncomputable def colGapMin (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) : ℝ :=
  ⨅ y' : {y' // y' ≠ y}, colGap u x y y'

end Learning.ZeroSumGame
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Game.RepeatedGame ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset
open scoped ProbabilityTheory
namespace Learning.RepeatedGame
open ZeroSumGame
variable {𝒳 𝒴 : Type*} [MeasurableSpace 𝒳] [MeasurableSpace 𝒴]

/-- A player of the repeated game with actions `𝒳`, against an opponent with actions `𝒴`: an
algorithm that observes, after each round, the opponent's action and the reward. -/
abbrev Player (𝒳 𝒴 : Type*) [MeasurableSpace 𝒳] [MeasurableSpace 𝒴] :=
  Algorithm Unit 𝒳 (𝒴 × ℝ)

/-- A round `(x, (y, r))` seen from the opponent: `(y, (x, r))`. -/
def Round.swapPlayers (r : Round Unit 𝒳 (𝒴 × ℝ)) : Round Unit 𝒴 (𝒳 × ℝ) :=
  ((), r.feedback.1, (r.action, r.feedback.2))

/-- A history seen from the opponent. -/
def Hist.swapPlayers {n : ℕ} (h : Hist Unit 𝒳 (𝒴 × ℝ) n) : Hist Unit 𝒴 (𝒳 × ℝ) n :=
  fun i ↦ Round.swapPlayers (h i)

@[fun_prop]
lemma Hist.measurable_swapPlayers (n : ℕ) :
    Measurable (Hist.swapPlayers (𝒳 := 𝒳) (𝒴 := 𝒴) (n := n)) := sorry

/-- A reward kernel: the law of the reward of a round given the past rounds and the two actions
of the round. -/
abbrev RewardKernel (𝒳 𝒴 : Type*) [MeasurableSpace 𝒳] [MeasurableSpace 𝒴] :=
  (n : ℕ) → Kernel (Hist Unit 𝒳 (𝒴 × ℝ) n × 𝒳 × 𝒴) ℝ

/-- The reward kernel has conditional mean `u x y`: the noise `r_t - u x_t y_t` is a martingale
difference sequence. -/
def RewardKernel.HasMean (R : RewardKernel 𝒳 𝒴) (u : 𝒳 → 𝒴 → ℝ) : Prop :=
  ∀ n (h : Hist Unit 𝒳 (𝒴 × ℝ) n) x y, ∫ r, r ∂(R n (h, x, y)) = u x y

/-- The rewards lie in the set `s` almost surely. -/
def RewardKernel.RewardsIn (R : RewardKernel 𝒳 𝒴) (s : Set ℝ) : Prop :=
  ∀ n (h : Hist Unit 𝒳 (𝒴 × ℝ) n) x y, ∀ᵐ r ∂(R n (h, x, y)), r ∈ s

/-- The environment of the learner playing against the opponent `opp` with reward kernel `R`: the
feedback of a round is `(y, r)` with `y` drawn from the policy of `opp` on the past rounds (seen
from the opponent) and `r` from `R`. -/
noncomputable def gameEnv (opp : Player 𝒴 𝒳) (R : RewardKernel 𝒳 𝒴) [∀ n, IsMarkovKernel (R n)] :
    Environment Unit 𝒳 (𝒴 × ℝ) where
  obs _ := Kernel.const _ (Measure.dirac ())
  feedback n :=
    ((opp.policy n).comap
      (fun p : (Hist Unit 𝒳 (𝒴 × ℝ) n × Unit) × 𝒳 ↦ (Hist.swapPlayers p.1.1, ())) (by fun_prop))
    ⊗ₖ ((R n).comap (fun q : ((Hist Unit 𝒳 (𝒴 × ℝ) n × Unit) × 𝒳) × 𝒴 ↦ (q.1.1.1, q.1.2, q.2))
      (by fun_prop))

/-- An uninformed learner, which observes only the rewards, as a player of the repeated game
(ignoring the opponent's actions in the feedback). -/
noncomputable def Player.ofUninformed (alg : Algorithm Unit 𝒳 ℝ) : Player 𝒳 𝒴 :=
  alg.comapFeedback Prod.snd measurable_snd

section Regret
omit [MeasurableSpace 𝒳] [MeasurableSpace 𝒴]
variable {Ω : Type*} {mΩ : MeasurableSpace Ω}

/-- The pure-strategy maximin regret `PSMR_T = E[∑_{t<T} (v* - u x_t y_t)]` of the run `(X, Y)`
under `P`. -/
noncomputable def psmr (u : 𝒳 → 𝒴 → ℝ) (X : ℕ → Ω → 𝒳) (Y : ℕ → Ω → 𝒴) (P : Measure Ω)
    (T : ℕ) : ℝ :=
  P[fun ω ↦ ∑ t ∈ range T, (pureMaximin u - u (X t ω) (Y t ω))]

end Regret
end Learning.RepeatedGame
end

-- ═══ Ito2026Adversarial.ILMTW2026.Theorem2 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset Real Learning Learning.ZeroSumGame
  Learning.RepeatedGame
universe u
namespace Ito2026Adversarial

/-- **Theorem 2** (Ito, Luo, Maiti, Tsuchiya, Wu 2026). There are `c > 0`, `Δ₀ > 0` and `T₀`
such that for all gaps `Δʳ, Δᶜ ∈ (0, Δ₀)`, all `T ≥ T₀` and every uninformed learner, there is a
`2 × 2` game `u` with utilities in `[-1, 1]` and a strict PSNE `(x*, y*)` with
`Δʳ_min = Δʳ`, `Δᶜ_min = Δᶜ`, an adversary and a reward noise (with conditional mean `u` and
rewards in `[-1, 1]`) under which the learner's PSMR after `T` rounds is at least
`c min {1 / (Δʳ Δᶜ), √T}`. -/
theorem exists_forall_psmr_ge :
    ∃ c : ℝ, 0 < c ∧ ∃ Δ₀ : ℝ, 0 < Δ₀ ∧ ∃ T₀ : ℕ,
      ∀ {Δr Δc : ℝ}, Δr ∈ Set.Ioo 0 Δ₀ → Δc ∈ Set.Ioo 0 Δ₀ → ∀ T : ℕ, T₀ ≤ T →
      ∀ alg : Algorithm Unit (Fin 2) ℝ,
      ∃ (u : Fin 2 → Fin 2 → ℝ) (x₀ y₀ : Fin 2), (∀ x y, u x y ∈ Set.Icc (-1) 1) ∧
        IsStrictPSNE u x₀ y₀ ∧ rowGapMin u x₀ y₀ = Δr ∧ colGapMin u x₀ y₀ = Δc ∧
        ∃ (opp : Player (Fin 2) (Fin 2)) (R : RewardKernel (Fin 2) (Fin 2))
          (_ : ∀ n, IsMarkovKernel (R n)),
          RewardKernel.HasMean R u ∧ RewardKernel.RewardsIn R (Set.Icc (-1) 1) ∧
          ∀ {Ω : Type u} {_mΩ : MeasurableSpace Ω} (P : Measure Ω) [IsProbabilityMeasure P]
            (X : ℕ → Ω → Fin 2) (Y : ℕ → Ω → Fin 2) (Rw : ℕ → Ω → ℝ),
            IsAlgEnvSeq (fun _ _ ↦ ()) X (fun t ω ↦ (Y t ω, Rw t ω))
              (Player.ofUninformed alg) (gameEnv opp R) P →
            c * min (1 / (Δr * Δc)) √T ≤ psmr u X Y P T := sorry

end Ito2026Adversarial
end
