module

public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.MeasureTheory.Order.Lattice
public import Mathlib.CategoryTheory.Countable
public import Mathlib.MeasureTheory.Constructions.Polish.Basic
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.Normed.Lp.MeasurableSpace
public import Mathlib.LinearAlgebra.Matrix.PosDef
public import Mathlib.Analysis.Convex.Basic
public import Mathlib.Analysis.Matrix.Order
public import Mathlib.Analysis.CStarAlgebra.Matrix
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.Topology.Instances.Matrix
public import Mathlib.Analysis.Matrix.MeasurableSpace
public import Mathlib.Analysis.RCLike.Lemmas
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Complex
public import Mathlib.MeasureTheory.Group.Arithmetic
public import Mathlib.Analysis.Convex.Hull
public import Mathlib.LinearAlgebra.Matrix.SchurComplement
public import Mathlib.Analysis.Convex.Caratheodory
public import Mathlib.Geometry.Convex.ConvexSpace.CompactSpaceStdSimplex
public import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
public import Mathlib.Topology.Algebra.Ring.Real
public import Mathlib.Data.Matrix.Mul
public import Mathlib.Order.ConditionallyCompleteLattice.Finset
public import Mathlib.Probability.Kernel.Composition.CompProd
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Algebra.BigOperators.Intervals
public import Mathlib.Analysis.Calculus.Gradient.Basic
public import Mathlib.Analysis.Calculus.LineDeriv.Basic
public import Mathlib.Analysis.Convex.Function
public import Mathlib.Topology.Algebra.Module.ContinuousLinearMap.PiProd
public import Mathlib.Analysis.SpecialFunctions.Log.Basic
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Inner
public import Mathlib.Probability.Distributions.Bernoulli
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Analysis.SpecialFunctions.Pow.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.ContinuousLinearMap
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Basic
public import Mathlib.Analysis.InnerProductSpace.Basic
public import Mathlib.Data.EReal.Basic
public import Mathlib.Analysis.Calculus.FDeriv.Measurable
public import Mathlib.Algebra.BigOperators.Field
public import Mathlib.Probability.IdentDistrib
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.MeasureTheory.Measure.GiryMonad
public import Mathlib.MeasureTheory.Measure.Dirac.Basic
public import Mathlib.MeasureTheory.Measure.Dirac.Def
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Order
public import Mathlib.Analysis.Matrix.PosDef
public import Mathlib.Probability.Moments.SubGaussian
public import Mathlib.MeasureTheory.Integral.Lebesgue.Add
public import Mathlib.Probability.Process.Filtration
public import Mathlib.Analysis.SpecialFunctions.Gaussian.FourierTransform
public import Mathlib.MeasureTheory.Measure.Lebesgue.EqHaar

/-! # Standalone extraction for `Ito2026Adversarial.exists_forall_exists_psmr_maximinLinUCB_le`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Real
end Real
namespace Finset
end Finset
namespace Learning
end Learning
namespace Function
end Function
namespace Matrix
end Matrix
namespace Bandits.Linear
end Bandits.Linear
namespace Learning.ZeroSumGame
end Learning.ZeroSumGame
namespace Learning.RepeatedGame
end Learning.RepeatedGame
namespace Ito2026Adversarial
end Ito2026Adversarial

-- ═══ LeanMachineLearning.SequentialLearning.Algorithm ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- One round of interaction: an observation, then an action, then a feedback. -/
abbrev Round (𝓞 𝓐 𝓨 : Type*) := 𝓞 × 𝓐 × 𝓨

/-- The action of a round. -/
def Round.action (r : Round 𝓞 𝓐 𝓨) : 𝓐 := r.2.1

/-- The feedback of a round. -/
def Round.feedback (r : Round 𝓞 𝓐 𝓨) : 𝓨 := r.2.2

/-- History of `n` complete rounds; `n = 0` is the empty history. -/
abbrev Hist (𝓞 𝓐 𝓨 : Type*) (n : ℕ) := Fin n → Round 𝓞 𝓐 𝓨

/-- A stochastic, sequential algorithm.
At each round, it sees an observation in `𝓞`, then takes an action in `𝓐`, and finally receives
feedback in `𝓨`. The action is a random function of the past rounds and the current observation. -/
@[ext]
structure Algorithm (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the action of round `n` given the past rounds and the current observation. -/
  policy : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n × 𝓞) 𝓐
  /-- The policy is a Markov kernel. -/
  [isMarkovKernel_policy : ∀ n, IsMarkovKernel (policy n)]

instance instIsMarkovKernelProdHistPolicy (alg : Algorithm 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (alg.policy n) :=
  alg.isMarkovKernel_policy n

/-- A stochastic environment.
At each round, an observation is drawn prior to the algorithm taking an action. Then the environment
provides feedback based on the observation and the action. -/
@[ext]
structure Environment (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the observation of round `n` given the past rounds. -/
  obs : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n) 𝓞
  /-- Law of the feedback of round `n` given the past rounds, the observation and the action. -/
  feedback : (n : ℕ) → Kernel ((Hist 𝓞 𝓐 𝓨 n × 𝓞) × 𝓐) 𝓨
  /-- The observation kernel is a Markov kernel. -/
  [isMarkovKernel_obs : ∀ n, IsMarkovKernel (obs n)]
  /-- The feedback kernel is a Markov kernel. -/
  [isMarkovKernel_feedback : ∀ n, IsMarkovKernel (feedback n)]

section IsAlgEnvSeq
variable {O : ℕ → Ω → 𝓞} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨} {P : Measure Ω} [IsFiniteMeasure P] {N : ℕ}

/-- History of the algorithm-environment sequence before time `n`: the rounds at
times `0, ..., n - 1`. -/
def history (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) : Hist 𝓞 𝓐 𝓨 n :=
  fun i ↦ (O i ω, A i ω, Y i ω)

/-- An algorithm-environment sequence: a sequence of observations, actions and feedbacks generated
by an algorithm interacting with an environment. -/
structure IsAlgEnvSeq
    (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)
    (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨)
    (P : Measure Ω) [IsFiniteMeasure P] : Prop where
  /-- The observation sequence is measurable. -/
  measurable_obs n : Measurable (O n) := by fun_prop
  /-- The action sequence is measurable. -/
  measurable_action n : Measurable (A n) := by fun_prop
  /-- The feedback sequence is measurable. -/
  measurable_feedback n : Measurable (Y n) := by fun_prop
  /-- The observation at time `n` has the correct conditional distribution given the history. -/
  hasCondDistrib_obs n :
    HasCondDistrib (O n) (history O A Y n) (env.obs n) P
  /-- The action at time `n` has the correct conditional distribution given the history and the
  observation at time `n`. -/
  hasCondDistrib_action n :
    HasCondDistrib (A n) (fun ω ↦ (history O A Y n ω, O n ω)) (alg.policy n) P
  /-- The feedback at time `n` has the correct conditional distribution given the history, the
  observation and the action at time `n`. -/
  hasCondDistrib_feedback n :
    HasCondDistrib (Y n) (fun ω ↦ ((history O A Y n ω, O n ω), A n ω)) (env.feedback n) P

end IsAlgEnvSeq
end Learning
end

-- ═══ LeanMachineLearning.SequentialLearning.Deterministic ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓞 𝓐 𝓨 : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨}
variable {nextA : (n : ℕ) → (Hist 𝓞 𝓐 𝓨 n × 𝓞) → 𝓐} {h_next : ∀ n, Measurable (nextA n)} {env : Environment 𝓞 𝓐 𝓨} {obs : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n) 𝓞} [∀ n, IsMarkovKernel (obs n)] {f : (n : ℕ) → ((Hist 𝓞 𝓐 𝓨 n × 𝓞) × 𝓐) → 𝓨} {hf : ∀ n, Measurable (f n)}

/-- A deterministic algorithm, which chooses the action given by the function `nextA`.
The initial action is `fun o ↦ nextA 0 (default, o)`. -/
@[simps]
noncomputable
def Algorithm.deterministic (nextA : (n : ℕ) → (Hist 𝓞 𝓐 𝓨 n × 𝓞) → 𝓐)
    (h_next : ∀ n, Measurable (nextA n)) :
    Algorithm 𝓞 𝓐 𝓨 where
  policy n := Kernel.deterministic (nextA n) (h_next n)

end Learning
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.SequentialLearning.Algorithms.Stateful ═══
@[expose] public section
open MeasureTheory ProbabilityTheory
namespace Learning
variable {𝓞 𝓐 𝓨 𝓞' 𝓐' 𝓨' σ Ω : Type*}

/-- The state after the `t` rounds of history `h`, starting from `s0` and updating at round `t`
by `upd t`. -/
def foldHistIdx (upd : ℕ → σ → Round 𝓞 𝓐 𝓨 → σ) (s0 : σ) : (t : ℕ) → Hist 𝓞 𝓐 𝓨 t → σ
  | 0, _ => s0
  | t + 1, h => upd t (foldHistIdx upd s0 t fun i ↦ h i.castSucc) (h (Fin.last t))

variable [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] [MeasurableSpace σ]

@[fun_prop]
lemma measurable_foldHistIdx {upd : ℕ → σ → Round 𝓞 𝓐 𝓨 → σ}
    (hupd : Measurable fun p : ℕ × σ × Round 𝓞 𝓐 𝓨 ↦ upd p.1 p.2.1 p.2.2) (s0 : σ) (t : ℕ) :
    Measurable (foldHistIdx upd s0 t) := sorry

/-- The deterministic stateful algorithm with initial state `s0`, state update `upd` and action
`a n s o` at round `n` from the state `s` and the observation `o`. -/
noncomputable def Algorithm.detStateful (s0 : σ) (upd : ℕ → σ → Round 𝓞 𝓐 𝓨 → σ)
    (hupd : Measurable fun p : ℕ × σ × Round 𝓞 𝓐 𝓨 ↦ upd p.1 p.2.1 p.2.2) (a : ℕ → σ → 𝓞 → 𝓐)
    (ha : Measurable fun p : ℕ × σ × 𝓞 ↦ a p.1 p.2.1 p.2.2) : Algorithm 𝓞 𝓐 𝓨 :=
  Algorithm.deterministic (fun n p ↦ a n (foldHistIdx upd s0 n p.1) p.2) fun n ↦
    ha.comp (measurable_const.prodMk
      (((measurable_foldHistIdx hupd s0 n).comp measurable_fst).prodMk measurable_snd))

variable [MeasurableSpace Ω]
end Learning
end

-- ═══ LeanMachineLearning.ForMathlib.MeasureTheory.Order.Lattice ═══
@[expose] public section
open Finset
variable {α δ : Type*} [MeasurableSpace δ] [SemilatticeInf α] {m : MeasurableSpace α} [MeasurableInf₂ α]
attribute [to_dual existing] MeasurableInf₂
end

-- ═══ LeanMachineLearning.ForMathlib.MeasureTheory.Order.MeasurableArg ═══
@[expose] public section
open Finset
variable {ι α : Type*} [LinearOrder α] [Fintype ι] [Nonempty ι] (f : ι → α)
namespace Function

/-- The maximum value of a tuple. -/
@[to_dual /-- The minimum value of a tuple. -/]
abbrev max : α := univ.sup' univ_nonempty f

end Function
section Argmax

@[to_dual]
lemma exists_argmax : ∃ i, f i = f.max := sorry

/-- The index of the maximum value of a tuple. -/
@[to_dual /-- The index of the minimum value of a tuple. -/]
noncomputable def argmax := (exists_argmax f).choose

variable [MeasurableSpace α]

@[to_dual (attr := fun_prop)]
lemma measurable_max [MeasurableSup₂ α] : Measurable (fun (t : ι → α) => t.max) := sorry

@[to_dual (attr := fun_prop)]
lemma measurable_argmax [MeasurableSpace ι] [MeasurableEq α] [MeasurableSup₂ α] :
    Measurable fun f : ι → α ↦ argmax f := sorry

end Argmax
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.SequentialLearning.Algorithms.Index ═══
@[expose] public section
open MeasureTheory ProbabilityTheory
namespace Learning
variable {𝓞 𝓐 𝓨 σ : Type*} [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] [MeasurableSpace σ] [Fintype 𝓐] [Nonempty 𝓐]

/-- The stateful index algorithm: the state is maintained by `upd` from `s0`, and at round `n`
an action maximizing `idx n s o` is played from the state `s` and the observation `o`. -/
noncomputable def Algorithm.statefulIndex (s0 : σ) (upd : ℕ → σ → Round 𝓞 𝓐 𝓨 → σ)
    (hupd : Measurable fun p : ℕ × σ × Round 𝓞 𝓐 𝓨 ↦ upd p.1 p.2.1 p.2.2) (idx : ℕ → σ → 𝓞 → 𝓐 → ℝ)
    (hidx : Measurable fun p : ℕ × σ × 𝓞 ↦ idx p.1 p.2.1 p.2.2) : Algorithm 𝓞 𝓐 𝓨 :=
  Algorithm.detStateful s0 upd hupd (fun n s o ↦ argmax (idx n s o)) (measurable_argmax.comp hidx)

end Learning
end

-- ═══ Ito2026Adversarial.Mathlib.Analysis.InnerProductSpace.Mahalanobis ═══
@[expose] public section
open Matrix
namespace Matrix
variable {ι : Type*} [Fintype ι]

/-- The squared Mahalanobis norm `‖x‖_A² = xᵀ A x`. -/
def mahalanobisSq (A : Matrix ι ι ℝ) (x : EuclideanSpace ℝ ι) : ℝ :=
  WithLp.ofLp x ⬝ᵥ A *ᵥ WithLp.ofLp x

end Matrix
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.DesignMatrix ═══
@[expose] public section
open Matrix Real
open scoped RealInnerProductSpace
namespace Learning
variable {ι : Type*}

/-- The design matrix `x xᵀ` of a point `x`. -/
def outerSelf (x : EuclideanSpace ℝ ι) : Matrix ι ι ℝ :=
  Matrix.vecMulVec (WithLp.ofLp x) (WithLp.ofLp x)

variable [Fintype ι]
variable [DecidableEq ι]
variable {ι : Type*} {𝒳 : Set (EuclideanSpace ℝ ι)} {x : EuclideanSpace ℝ ι} {A : Matrix ι ι ℝ} {R : ℝ}
variable [Fintype ι]
variable [DecidableEq ι]
end Learning
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Online.Bandit.Linear.Ridge ═══
@[expose] public section
open MeasureTheory Finset Matrix Learning
open scoped RealInnerProductSpace
namespace Bandits.Linear
variable {ι : Type*}

/-- The ridge regression state `(V, b)`: the (regularized) design matrix and the sum of the
features weighted by the rewards. -/
abbrev RidgeState (ι : Type*) := Matrix ι ι ℝ × EuclideanSpace ℝ ι

/-- The ridge regression update `(V, b) ↦ (V + x xᵀ, b + y x)` with the feature `x` and the
reward `y`. -/
noncomputable def ridgeUpdate (s : RidgeState ι) (x : EuclideanSpace ℝ ι) (y : ℝ) :
    RidgeState ι :=
  (s.1 + outerSelf x, s.2 + y • x)

section Estimate
variable [Fintype ι] [DecidableEq ι]

/-- The ridge regression estimate `θ̂ = V⁻¹ b`. -/
noncomputable def ridgeEstimate (s : RidgeState ι) : EuclideanSpace ℝ ι :=
  WithLp.toLp _ (s.1⁻¹ *ᵥ WithLp.ofLp s.2)

/-- The optimistic index `⟪v, θ̂⟫ + β ‖v‖_{V⁻¹}` of the feature vector `v`, from the ridge state
`(V, b)` and the confidence radius `β`. -/
noncomputable def ucbIndex (β : ℝ) (s : RidgeState ι) (v : EuclideanSpace ℝ ι) : ℝ :=
  ⟪v, ridgeEstimate s⟫ + β * √(mahalanobisSq s.1⁻¹ v)

end Estimate
end Bandits.Linear
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Game.ZeroSum ═══
@[expose] public section
open Finset
namespace Learning.ZeroSumGame
variable {𝒳 𝒴 : Type*} {u : 𝒳 → 𝒴 → ℝ} {x : 𝒳} {y : 𝒴}

/-- The pure-strategy maximin value `v* = max_x min_y u x y`. -/
noncomputable def pureMaximin (u : 𝒳 → 𝒴 → ℝ) : ℝ := ⨆ x, ⨅ y, u x y

/-- The gap `Δ_{xy} = v* - u x y` of the action pair `(x, y)` to the pure-strategy maximin value
(possibly negative). -/
noncomputable def pairGap (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) : ℝ := pureMaximin u - u x y

end Learning.ZeroSumGame
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Game.RepeatedGame ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset
open scoped ProbabilityTheory
namespace Learning.RepeatedGame
open ZeroSumGame
variable {𝒳 𝒴 : Type*} [MeasurableSpace 𝒳] [MeasurableSpace 𝒴]

/-- A player of the repeated game with actions `𝒳`, against an opponent with actions `𝒴`: an
algorithm that observes, after each round, the opponent's action and the reward. -/
abbrev Player (𝒳 𝒴 : Type*) [MeasurableSpace 𝒳] [MeasurableSpace 𝒴] :=
  Algorithm Unit 𝒳 (𝒴 × ℝ)

/-- A round `(x, (y, r))` seen from the opponent: `(y, (x, r))`. -/
def Round.swapPlayers (r : Round Unit 𝒳 (𝒴 × ℝ)) : Round Unit 𝒴 (𝒳 × ℝ) :=
  ((), r.feedback.1, (r.action, r.feedback.2))

/-- A history seen from the opponent. -/
def Hist.swapPlayers {n : ℕ} (h : Hist Unit 𝒳 (𝒴 × ℝ) n) : Hist Unit 𝒴 (𝒳 × ℝ) n :=
  fun i ↦ Round.swapPlayers (h i)

@[fun_prop]
lemma Hist.measurable_swapPlayers (n : ℕ) :
    Measurable (Hist.swapPlayers (𝒳 := 𝒳) (𝒴 := 𝒴) (n := n)) := sorry

/-- A reward kernel: the law of the reward of a round given the past rounds and the two actions
of the round. -/
abbrev RewardKernel (𝒳 𝒴 : Type*) [MeasurableSpace 𝒳] [MeasurableSpace 𝒴] :=
  (n : ℕ) → Kernel (Hist Unit 𝒳 (𝒴 × ℝ) n × 𝒳 × 𝒴) ℝ

/-- The reward kernel has conditional mean `u x y`: the noise `r_t - u x_t y_t` is a martingale
difference sequence. -/
def RewardKernel.HasMean (R : RewardKernel 𝒳 𝒴) (u : 𝒳 → 𝒴 → ℝ) : Prop :=
  ∀ n (h : Hist Unit 𝒳 (𝒴 × ℝ) n) x y, ∫ r, r ∂(R n (h, x, y)) = u x y

/-- The rewards lie in the set `s` almost surely. -/
def RewardKernel.RewardsIn (R : RewardKernel 𝒳 𝒴) (s : Set ℝ) : Prop :=
  ∀ n (h : Hist Unit 𝒳 (𝒴 × ℝ) n) x y, ∀ᵐ r ∂(R n (h, x, y)), r ∈ s

/-- The environment of the learner playing against the opponent `opp` with reward kernel `R`: the
feedback of a round is `(y, r)` with `y` drawn from the policy of `opp` on the past rounds (seen
from the opponent) and `r` from `R`. -/
noncomputable def gameEnv (opp : Player 𝒴 𝒳) (R : RewardKernel 𝒳 𝒴) [∀ n, IsMarkovKernel (R n)] :
    Environment Unit 𝒳 (𝒴 × ℝ) where
  obs _ := Kernel.const _ (Measure.dirac ())
  feedback n :=
    ((opp.policy n).comap
      (fun p : (Hist Unit 𝒳 (𝒴 × ℝ) n × Unit) × 𝒳 ↦ (Hist.swapPlayers p.1.1, ())) (by fun_prop))
    ⊗ₖ ((R n).comap (fun q : ((Hist Unit 𝒳 (𝒴 × ℝ) n × Unit) × 𝒳) × 𝒴 ↦ (q.1.1.1, q.1.2, q.2))
      (by fun_prop))

section Regret
omit [MeasurableSpace 𝒳] [MeasurableSpace 𝒴]
variable {Ω : Type*} {mΩ : MeasurableSpace Ω}

/-- The pure-strategy maximin regret `PSMR_T = E[∑_{t<T} (v* - u x_t y_t)]` of the run `(X, Y)`
under `P`. -/
noncomputable def psmr (u : 𝒳 → 𝒴 → ℝ) (X : ℕ → Ω → 𝒳) (Y : ℕ → Ω → 𝒴) (P : Measure Ω)
    (T : ℕ) : ℝ :=
  P[fun ω ↦ ∑ t ∈ range T, (pureMaximin u - u (X t ω) (Y t ω))]

end Regret
end Learning.RepeatedGame
end

-- ═══ Ito2026Adversarial.ILMTW2026.Setting ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset Learning Learning.ZeroSumGame Learning.RepeatedGame
  Matrix Real
open scoped RealInnerProductSpace
namespace Ito2026Adversarial

/-- `Δ` is a threshold for the positive pair gaps of the game `u`:
`v* - u x y ∈ (-∞, 0] ∪ [Δ, ∞)` for all `(x, y)` (the parameter `Δ^lin` of the paper). -/
def IsGapThreshold {𝒳 𝒴 : Type*} (u : 𝒳 → 𝒴 → ℝ) (Δ : ℝ) : Prop :=
  ∀ x y, pairGap u x y ≤ 0 ∨ Δ ≤ pairGap u x y

section Bilinear
variable {ιx ιy : Type*} [Fintype ιx] [Fintype ιy]

/-- The bilinear utility `u(x, y) = ⟪x, A y⟫ = xᵀ A y`. -/
noncomputable def bilinearUtility (A : Matrix ιx ιy ℝ) (x : EuclideanSpace ℝ ιx)
    (y : EuclideanSpace ℝ ιy) : ℝ :=
  WithLp.ofLp x ⬝ᵥ (A *ᵥ WithLp.ofLp y)

variable {𝒳 𝒴 : Type*}

/-- The bilinear game with matrix `A` on the finite action sets `𝒳`, `𝒴` with features
`φ : 𝒳 → ℝ^{d_x}`, `ψ : 𝒴 → ℝ^{d_y}`: `u x y = ⟪φ x, A ψ y⟫`. -/
noncomputable def bilinearGame (φ : 𝒳 → EuclideanSpace ℝ ιx) (ψ : 𝒴 → EuclideanSpace ℝ ιy)
    (A : Matrix ιx ιy ℝ) : 𝒳 → 𝒴 → ℝ :=
  fun x y ↦ bilinearUtility A (φ x) (ψ y)

/-- The assumptions of the paper on a bilinear game: the actions have norm at most `1` and span
their spaces, and the matrix has operator norm at most `1` (so that `u x y ∈ [-1, 1]`). -/
structure IsBilinearGame (φ : 𝒳 → EuclideanSpace ℝ ιx) (ψ : 𝒴 → EuclideanSpace ℝ ιy)
    (A : Matrix ιx ιy ℝ) : Prop where
  norm_le_x : ∀ x, ‖φ x‖ ≤ 1
  norm_le_y : ∀ y, ‖ψ y‖ ≤ 1
  span_x : Submodule.span ℝ (Set.range φ) = ⊤
  span_y : Submodule.span ℝ (Set.range ψ) = ⊤
  opNorm_le : ∀ y : EuclideanSpace ℝ ιy,
    ‖(WithLp.toLp 2 (A *ᵥ WithLp.ofLp y) : EuclideanSpace ℝ ιx)‖ ≤ ‖y‖

omit [Fintype ιx] [Fintype ιy] in
/-- The feature `vec(x yᵀ)` of the action pair `(x, y)`, a vector indexed by `ιx × ιy`. -/
noncomputable def pairFeature (x : EuclideanSpace ℝ ιx) (y : EuclideanSpace ℝ ιy) :
    EuclideanSpace ℝ (ιx × ιy) :=
  WithLp.toLp _ fun ij ↦ x ij.1 * y ij.2

end Bilinear
section LinUCB
variable {ιx ιy : Type*} [Fintype ιx] [Fintype ιy] {𝒳 𝒴 : Type*} [MeasurableSpace 𝒳] [MeasurableSpace 𝒴] (φ : 𝒳 → EuclideanSpace ℝ ιx) (ψ : 𝒴 → EuclideanSpace ℝ ιy)

/-- The state of the ridge regression of Maximin-LinUCB: the matrix `V` and the vector `b` (the
library's ridge regression state for features indexed by `ιx × ιy`). -/
abbrev LinState (ιx ιy : Type*) := Bandits.Linear.RidgeState (ιx × ιy)

/-- The ridge regression update `(V, b) ↦ (V + a aᵀ, b + r a)` for the feature
`a = vec(φ x (ψ y)ᵀ)` of the round and its reward `r` (the library's `ridgeUpdate`). -/
noncomputable def linUpdate (s : LinState ιx ιy) (r : Round Unit 𝒳 (𝒴 × ℝ)) : LinState ιx ιy :=
  Bandits.Linear.ridgeUpdate s (pairFeature (φ r.action) (ψ r.feedback.1)) r.feedback.2

variable [Countable 𝒳] [MeasurableSingletonClass 𝒳] [Countable 𝒴] [MeasurableSingletonClass 𝒴]

omit [Fintype ιx] [Fintype ιy] in
@[fun_prop]
lemma measurable_linUpdate [Finite ιx] [Finite ιy] {X : Type*} [MeasurableSpace X]
    {s : X → LinState ιx ιy} {r : X → Round Unit 𝒳 (𝒴 × ℝ)} (hs : Measurable s)
    (hr : Measurable r) : Measurable fun x ↦ linUpdate φ ψ (s x) (r x) := sorry

variable [DecidableEq ιx] [DecidableEq ιy]

/-- The optimistic index `U(x, y) = ⟪vec(x yᵀ), V⁻¹ b⟫ + β ‖vec(x yᵀ)‖_{V⁻¹}` of the pair
`(x, y)` from the ridge state `(V, b)` and the radius `β` (the library's optimistic index
`ucbIndex` of the feature `vec(x yᵀ)`, with the ridge estimate `V⁻¹ b = ridgeEstimate s`). -/
noncomputable def linIndex (β : ℝ) (s : LinState ιx ιy) (x : EuclideanSpace ℝ ιx)
    (y : EuclideanSpace ℝ ιy) : ℝ :=
  Bandits.Linear.ucbIndex β s (pairFeature x y)

@[fun_prop]
lemma measurable_linIndex {X : Type*} [MeasurableSpace X] {β : X → ℝ} {s : X → LinState ιx ιy}
    (hβ : Measurable β) (hs : Measurable s) (x : EuclideanSpace ℝ ιx) (y : EuclideanSpace ℝ ιy) :
    Measurable fun q ↦ linIndex (β q) (s q) x y := sorry

variable [Fintype 𝒳] [Fintype 𝒴] [Nonempty 𝒳] [Nonempty 𝒴]

/-- **Algorithm 4** (Maximin-LinUCB) with regularization `λ` and radii `β`: an informed
deterministic player which, at round `n`, plays the pure maximin action `linAction` of the
optimistic indices built from the ridge regression state
`(V_n, b_n) = (λ I + ∑_{s<n} a_s a_sᵀ, ∑_{s<n} r_s a_s)` and the radius `β n` (a stateful index
algorithm). -/
noncomputable def maximinLinUCB (lam : ℝ) (β : ℕ → ℝ) : Player 𝒳 𝒴 :=
  Algorithm.statefulIndex (lam • 1, 0) (fun _ ↦ linUpdate φ ψ) (by fun_prop)
    (fun n s _ x ↦ (fun y ↦ linIndex (β n) s (φ x) (ψ y)).min) (by fun_prop)

end LinUCB
end Ito2026Adversarial
end

-- ═══ Ito2026Adversarial.ILMTW2026.Theorem6 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset Real Learning Learning.ZeroSumGame
  Learning.RepeatedGame Matrix
universe u
namespace Ito2026Adversarial

/-- **Theorem 6** (Ito, Luo, Maiti, Tsuchiya, Wu 2026; informal version of Theorem 12). There
is a universal constant `C` such that for every bilinear game and every horizon `T ≥ 2` there are
parameters `(λ, β)` of Maximin-LinUCB such that, against every adaptive adversary and every reward
noise with conditional mean `u` and rewards in `[-1, 1]`, `PSMR_T ≤ C d_x d_y √T log T` and
`PSMR_T ≤ C d_x² d_y² log² T / Δ^lin` for every gap threshold `Δ^lin > 0` of the game. -/
theorem exists_forall_exists_psmr_maximinLinUCB_le :
    ∃ C : ℝ, 0 < C ∧
      ∀ {mx my dx dy : ℕ} [NeZero mx] [NeZero my] (φ : Fin mx → EuclideanSpace ℝ (Fin dx))
        (ψ : Fin my → EuclideanSpace ℝ (Fin dy)) (A : Matrix (Fin dx) (Fin dy) ℝ),
        IsBilinearGame φ ψ A → ∀ (T : ℕ), 2 ≤ T →
      ∃ (lam : ℝ) (β : ℕ → ℝ),
      ∀ (opp : Player (Fin my) (Fin mx)) (R : RewardKernel (Fin mx) (Fin my))
        [∀ n, IsMarkovKernel (R n)],
      RewardKernel.HasMean R (bilinearGame φ ψ A) → RewardKernel.RewardsIn R (Set.Icc (-1) 1) →
      ∀ {Ω : Type u} {_mΩ : MeasurableSpace Ω} (P : Measure Ω) [IsProbabilityMeasure P]
        (X : ℕ → Ω → Fin mx) (Y : ℕ → Ω → Fin my) (Rw : ℕ → Ω → ℝ),
      IsAlgEnvSeq (fun _ _ ↦ ()) X (fun t ω ↦ (Y t ω, Rw t ω)) (maximinLinUCB φ ψ lam β)
        (gameEnv opp R) P →
        psmr (bilinearGame φ ψ A) X Y P T ≤ C * (dx * dy * √T * log T) ∧
        ∀ Δ : ℝ, 0 < Δ → IsGapThreshold (bilinearGame φ ψ A) Δ →
          psmr (bilinearGame φ ψ A) X Y P T ≤ C * (dx ^ 2 * dy ^ 2 * log T ^ 2 / Δ) := sorry

end Ito2026Adversarial
end
