module

public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.MeasureTheory.Order.Lattice
public import Mathlib.CategoryTheory.Countable
public import Mathlib.MeasureTheory.Constructions.Polish.Basic
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.Analysis.Convex.Basic
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.Normed.Lp.MeasurableSpace
public import Mathlib.Geometry.Convex.ConvexSpace.CompactSpaceStdSimplex
public import Mathlib.MeasureTheory.Measure.GiryMonad
public import Mathlib.MeasureTheory.Measure.Dirac.Basic
public import Mathlib.MeasureTheory.Measure.Dirac.Def
public import Mathlib.Algebra.BigOperators.Field
public import Mathlib.Probability.IdentDistrib
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Order
public import Mathlib.Analysis.InnerProductSpace.Basic
public import Mathlib.Data.EReal.Basic
public import Mathlib.Analysis.SpecialFunctions.Pow.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.ContinuousLinearMap
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Basic
public import Mathlib.Analysis.Calculus.FDeriv.Measurable
public import Mathlib.Analysis.Calculus.Gradient.Basic
public import Mathlib.Analysis.Convex.Hull
public import Mathlib.Topology.Instances.Matrix
public import Mathlib.LinearAlgebra.Matrix.SchurComplement
public import Mathlib.Analysis.Matrix.Order
public import Mathlib.Analysis.CStarAlgebra.Matrix
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.LinearAlgebra.Matrix.PosDef
public import Mathlib.Analysis.Matrix.MeasurableSpace
public import Mathlib.Analysis.RCLike.Lemmas
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Complex
public import Mathlib.MeasureTheory.Group.Arithmetic
public import Mathlib.Analysis.Convex.Caratheodory
public import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
public import Mathlib.Topology.Algebra.Ring.Real
public import Mathlib.Data.Matrix.Mul
public import Mathlib.Order.ConditionallyCompleteLattice.Finset
public import Mathlib.Probability.Kernel.Composition.CompProd
public import Mathlib.Algebra.BigOperators.Intervals
public import Mathlib.Analysis.Calculus.LineDeriv.Basic
public import Mathlib.Analysis.Convex.Function
public import Mathlib.Topology.Algebra.Module.ContinuousLinearMap.PiProd
public import Mathlib.Analysis.SpecialFunctions.Log.Basic
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Inner
public import Mathlib.Probability.Distributions.Bernoulli
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Analysis.Matrix.PosDef
public import Mathlib.Probability.Moments.SubGaussian
public import Mathlib.MeasureTheory.Integral.Lebesgue.Add
public import Mathlib.Probability.Process.Filtration
public import Mathlib.Analysis.SpecialFunctions.Gaussian.FourierTransform
public import Mathlib.MeasureTheory.Measure.Lebesgue.EqHaar
public import Mathlib.Analysis.Complex.ExponentialBounds
public import Mathlib.Analysis.SpecialFunctions.Log.Base
public import Mathlib.Analysis.Convex.Integral
public import Mathlib.Analysis.Convex.SpecificFunctions.Pow
public import Mathlib.NumberTheory.Harmonic.Bounds
public import Mathlib.Analysis.MeanInequalities
public import Mathlib.Analysis.MeanInequalitiesPow
public import Mathlib.Analysis.Convex.SpecificFunctions.Basic
public import Mathlib.Analysis.SpecialFunctions.Pow.Deriv
public import Mathlib.Analysis.Calculus.MeanValue

/-! # Standalone extraction for `Ito2026Adversarial.forall_exists_psmr_tsallisSPMPaper_le`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Real
end Real
namespace Finset
end Finset
namespace Learning
end Learning
namespace Function
end Function
namespace Matrix
end Matrix
namespace Learning.ZeroSumGame
end Learning.ZeroSumGame
namespace Learning.RepeatedGame
end Learning.RepeatedGame
namespace Ito2026Adversarial
end Ito2026Adversarial

-- ═══ LeanMachineLearning.SequentialLearning.Algorithm ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- One round of interaction: an observation, then an action, then a feedback. -/
abbrev Round (𝓞 𝓐 𝓨 : Type*) := 𝓞 × 𝓐 × 𝓨

/-- The observation of a round. -/
def Round.obs (r : Round 𝓞 𝓐 𝓨) : 𝓞 := r.1

/-- The action of a round. -/
def Round.action (r : Round 𝓞 𝓐 𝓨) : 𝓐 := r.2.1

/-- The feedback of a round. -/
def Round.feedback (r : Round 𝓞 𝓐 𝓨) : 𝓨 := r.2.2

/-- History of `n` complete rounds; `n = 0` is the empty history. -/
abbrev Hist (𝓞 𝓐 𝓨 : Type*) (n : ℕ) := Fin n → Round 𝓞 𝓐 𝓨

/-- A stochastic, sequential algorithm.
At each round, it sees an observation in `𝓞`, then takes an action in `𝓐`, and finally receives
feedback in `𝓨`. The action is a random function of the past rounds and the current observation. -/
@[ext]
structure Algorithm (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the action of round `n` given the past rounds and the current observation. -/
  policy : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n × 𝓞) 𝓐
  /-- The policy is a Markov kernel. -/
  [isMarkovKernel_policy : ∀ n, IsMarkovKernel (policy n)]

instance instIsMarkovKernelProdHistPolicy (alg : Algorithm 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (alg.policy n) :=
  alg.isMarkovKernel_policy n

/-- A stochastic environment.
At each round, an observation is drawn prior to the algorithm taking an action. Then the environment
provides feedback based on the observation and the action. -/
@[ext]
structure Environment (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the observation of round `n` given the past rounds. -/
  obs : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n) 𝓞
  /-- Law of the feedback of round `n` given the past rounds, the observation and the action. -/
  feedback : (n : ℕ) → Kernel ((Hist 𝓞 𝓐 𝓨 n × 𝓞) × 𝓐) 𝓨
  /-- The observation kernel is a Markov kernel. -/
  [isMarkovKernel_obs : ∀ n, IsMarkovKernel (obs n)]
  /-- The feedback kernel is a Markov kernel. -/
  [isMarkovKernel_feedback : ∀ n, IsMarkovKernel (feedback n)]

section IsAlgEnvSeq
variable {O : ℕ → Ω → 𝓞} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨} {P : Measure Ω} [IsFiniteMeasure P] {N : ℕ}

/-- History of the algorithm-environment sequence before time `n`: the rounds at
times `0, ..., n - 1`. -/
def history (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) : Hist 𝓞 𝓐 𝓨 n :=
  fun i ↦ (O i ω, A i ω, Y i ω)

/-- An algorithm-environment sequence: a sequence of observations, actions and feedbacks generated
by an algorithm interacting with an environment. -/
structure IsAlgEnvSeq
    (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)
    (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨)
    (P : Measure Ω) [IsFiniteMeasure P] : Prop where
  /-- The observation sequence is measurable. -/
  measurable_obs n : Measurable (O n) := by fun_prop
  /-- The action sequence is measurable. -/
  measurable_action n : Measurable (A n) := by fun_prop
  /-- The feedback sequence is measurable. -/
  measurable_feedback n : Measurable (Y n) := by fun_prop
  /-- The observation at time `n` has the correct conditional distribution given the history. -/
  hasCondDistrib_obs n :
    HasCondDistrib (O n) (history O A Y n) (env.obs n) P
  /-- The action at time `n` has the correct conditional distribution given the history and the
  observation at time `n`. -/
  hasCondDistrib_action n :
    HasCondDistrib (A n) (fun ω ↦ (history O A Y n ω, O n ω)) (alg.policy n) P
  /-- The feedback at time `n` has the correct conditional distribution given the history, the
  observation and the action at time `n`. -/
  hasCondDistrib_feedback n :
    HasCondDistrib (Y n) (fun ω ↦ ((history O A Y n ω, O n ω), A n ω)) (env.feedback n) P

end IsAlgEnvSeq
end Learning
end

-- ═══ LeanMachineLearning.SequentialLearning.Comap ═══
@[expose] public section
open MeasureTheory ProbabilityTheory
namespace Learning
variable {𝓞 𝓞' 𝓞'' 𝓐 𝓐' 𝓐'' 𝓨 𝓨' 𝓨'' Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓞' : MeasurableSpace 𝓞'} {m𝓞'' : MeasurableSpace 𝓞''} {m𝓐 : MeasurableSpace 𝓐} {m𝓐' : MeasurableSpace 𝓐'} {m𝓐'' : MeasurableSpace 𝓐''} {m𝓨 : MeasurableSpace 𝓨} {m𝓨' : MeasurableSpace 𝓨'} {m𝓨'' : MeasurableSpace 𝓨''} {mΩ : MeasurableSpace Ω} {fo : 𝓞 → 𝓞'} {fa : 𝓐 → 𝓐'} {fy : 𝓨 → 𝓨'} {go : 𝓞' → 𝓞''} {ga : 𝓐' → 𝓐''} {gy : 𝓨' → 𝓨''}
section Map

/-- Transport a round along maps of the observation, the action and the feedback. -/
def Round.map (fo : 𝓞 → 𝓞') (fa : 𝓐 → 𝓐') (fy : 𝓨 → 𝓨') (r : Round 𝓞 𝓐 𝓨) : Round 𝓞' 𝓐' 𝓨' :=
  (fo r.obs, fa r.action, fy r.feedback)

/-- Transport a history round-wise. -/
def Hist.map (fo : 𝓞 → 𝓞') (fa : 𝓐 → 𝓐') (fy : 𝓨 → 𝓨') {n : ℕ} (h : Hist 𝓞 𝓐 𝓨 n) :
    Hist 𝓞' 𝓐' 𝓨' n :=
  fun i ↦ Round.map fo fa fy (h i)

@[fun_prop]
lemma Hist.measurable_map (hfo : Measurable fo) (hfa : Measurable fa) (hfy : Measurable fy)
    (n : ℕ) :
    Measurable (Hist.map fo fa fy (n := n)) := sorry

/-- Transport the feedback of a history. -/
abbrev Hist.mapFeedback (f : 𝓨 → 𝓨') {n : ℕ} (h : Hist 𝓞 𝓐 𝓨 n) : Hist 𝓞 𝓐 𝓨' n :=
  Hist.map id id f h

end Map
section Comap

/-- The algorithm with observations in `𝓞'` and feedbacks in `𝓨'` obtained from
`alg : Algorithm 𝓞 𝓐 𝓨` by transforming the pair (past rounds, current observation) by `F n` at
each round `n` before applying the policy of `alg`.

This is the primitive transport operation on algorithms: `Algorithm.comapObs` and
`Algorithm.comapFeedback` are the special cases in which `F n` is a round-wise map of the
observation and of the feedback. -/
def Algorithm.comap (alg : Algorithm 𝓞 𝓐 𝓨)
    (F : (n : ℕ) → Hist 𝓞' 𝓐 𝓨' n × 𝓞' → Hist 𝓞 𝓐 𝓨 n × 𝓞) (hF : ∀ n, Measurable (F n)) :
    Algorithm 𝓞' 𝓐 𝓨' where
  policy n := (alg.policy n).comap (F n) (hF n)

section ComapFeedback
variable {g : 𝓨' → 𝓨}

/-- The algorithm that sees `g y` when the feedback of a past round is `y`. -/
def Algorithm.comapFeedback (alg : Algorithm 𝓞 𝓐 𝓨) (g : 𝓨' → 𝓨)
    (hg : Measurable g := by fun_prop) : Algorithm 𝓞 𝓐 𝓨' :=
  alg.comap (fun _ p ↦ (Hist.mapFeedback g p.1, p.2)) fun _ ↦ by fun_prop

end ComapFeedback
end Comap
end Learning
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.SequentialLearning.Algorithms.Stateful ═══
@[expose] public section
open MeasureTheory ProbabilityTheory
namespace Learning
variable {𝓞 𝓐 𝓨 𝓞' 𝓐' 𝓨' σ Ω : Type*}

/-- The state after the `t` rounds of history `h`, starting from `s0` and updating at round `t`
by `upd t`. -/
def foldHistIdx (upd : ℕ → σ → Round 𝓞 𝓐 𝓨 → σ) (s0 : σ) : (t : ℕ) → Hist 𝓞 𝓐 𝓨 t → σ
  | 0, _ => s0
  | t + 1, h => upd t (foldHistIdx upd s0 t fun i ↦ h i.castSucc) (h (Fin.last t))

variable [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] [MeasurableSpace σ]

@[fun_prop]
lemma measurable_foldHistIdx {upd : ℕ → σ → Round 𝓞 𝓐 𝓨 → σ}
    (hupd : Measurable fun p : ℕ × σ × Round 𝓞 𝓐 𝓨 ↦ upd p.1 p.2.1 p.2.2) (s0 : σ) (t : ℕ) :
    Measurable (foldHistIdx upd s0 t) := sorry

/-- The stateful algorithm with initial state `s0`, state update `upd` and policy `π`: the action
at round `n` is drawn from `π n` applied to the current state and the current observation. -/
noncomputable def Algorithm.stateful (s0 : σ) (upd : ℕ → σ → Round 𝓞 𝓐 𝓨 → σ)
    (hupd : Measurable fun p : ℕ × σ × Round 𝓞 𝓐 𝓨 ↦ upd p.1 p.2.1 p.2.2)
    (π : ℕ → Kernel (σ × 𝓞) 𝓐) [∀ n, IsMarkovKernel (π n)] : Algorithm 𝓞 𝓐 𝓨 where
  policy n := (π n).comap (fun p ↦ (foldHistIdx upd s0 n p.1, p.2))
    (((measurable_foldHistIdx hupd s0 n).comp measurable_fst).prodMk measurable_snd)

variable [MeasurableSpace Ω]
end Learning
end

-- ═══ LeanMachineLearning.ForMathlib.MeasureTheory.Order.Lattice ═══
@[expose] public section
open Finset
variable {α δ : Type*} [MeasurableSpace δ] [SemilatticeInf α] {m : MeasurableSpace α} [MeasurableInf₂ α]
attribute [to_dual existing] MeasurableInf₂
end

-- ═══ LeanMachineLearning.ForMathlib.MeasureTheory.Order.MeasurableArg ═══
@[expose] public section
open Finset
variable {ι α : Type*} [LinearOrder α] [Fintype ι] [Nonempty ι] (f : ι → α)
namespace Function

/-- The maximum value of a tuple. -/
@[to_dual /-- The minimum value of a tuple. -/]
abbrev max : α := univ.sup' univ_nonempty f

end Function
end

-- ═══ Ito2026Adversarial.Mathlib.Analysis.Convex.Simplex ═══
@[expose] public section
open MeasureTheory
namespace Learning
variable {ι : Type*} [Fintype ι]

/-- The probability simplex `{p | ∀ i, 0 ≤ p i, ∑ i, p i = 1}` of `EuclideanSpace ℝ ι`. -/
def simplex (ι : Type*) [Fintype ι] : Set (EuclideanSpace ℝ ι) :=
  {p | (∀ i, 0 ≤ p i) ∧ ∑ i, p i = 1}

/-- A point of the simplex is a function on `ι`: `p i` is its `i`-th coordinate. -/
instance instCoeFunElemEuclideanSpaceRealSimplexForall : CoeFun (simplex ι) (fun _ ↦ ι → ℝ) := ⟨fun p ↦ (p : EuclideanSpace ℝ ι).ofLp⟩

@[fun_prop]
lemma measurable_coe_simplex : Measurable fun p : simplex ι ↦ (p : ι → ℝ) := sorry

/-- The uniform distribution `(1/|ι|, …, 1/|ι|)` of `EuclideanSpace ℝ ι`. -/
noncomputable def uniformVec (ι : Type*) [Fintype ι] : EuclideanSpace ℝ ι :=
  (EuclideanSpace.equiv ι ℝ).symm fun _ ↦ (Fintype.card ι : ℝ)⁻¹

lemma uniformVec_mem_simplex [Nonempty ι] : uniformVec ι ∈ simplex ι := sorry

/-- The uniform distribution, as an element of the simplex. -/
noncomputable def uniformSimplex (ι : Type*) [Fintype ι] [Nonempty ι] : simplex ι :=
  ⟨uniformVec ι, uniformVec_mem_simplex⟩

instance instNonemptyElemEuclideanSpaceRealSimplex [Nonempty ι] : Nonempty (simplex ι) := ⟨uniformSimplex ι⟩

end Learning
end

-- ═══ Ito2026Adversarial.Mathlib.MeasureTheory.Measure.Weighted ═══
@[expose] public section
open scoped ENNReal
namespace MeasureTheory
variable {ι : Type*} [Fintype ι] [MeasurableSpace ι] {p q : ι → ℝ}

/-- The measure on `ι` with weights `p`: `∑ i, p i • δ_i` (negative weights count as `0`). -/
noncomputable def weightedMeasure (p : ι → ℝ) : Measure ι :=
  ∑ i, ENNReal.ofReal (p i) • Measure.dirac i

/-- The weighted measure of a probability vector is a probability measure. -/
lemma isProbabilityMeasure_weightedMeasure (hp0 : ∀ i, 0 ≤ p i) (hp1 : ∑ i, p i = 1) :
    IsProbabilityMeasure (weightedMeasure p) := sorry

/-- The map `p ↦ weightedMeasure p` is measurable. -/
lemma measurable_weightedMeasure : Measurable (weightedMeasure (ι := ι)) := sorry

end MeasureTheory
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Online.Bandit.ImportanceWeighting ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset
namespace Learning
variable {ι : Type*} [Fintype ι] [MeasurableSpace ι]

/-- The kernel sampling an index `i ∼ p` from a point `p` of the simplex. -/
noncomputable def simplexKernel (ι : Type*) [Fintype ι] [MeasurableSpace ι] :
    Kernel (simplex ι) ι where
  toFun p := weightedMeasure p
  measurable' := measurable_weightedMeasure.comp (by fun_prop)

instance instIsMarkovKernelElemEuclideanSpaceRealSimplexSimplexKernel : IsMarkovKernel (simplexKernel ι) :=
  ⟨fun p ↦ isProbabilityMeasure_weightedMeasure p.2.1 p.2.2⟩

end Learning
end

-- ═══ Ito2026Adversarial.Mathlib.MeasureTheory.MeasurableSpace.ToSet ═══
@[expose] public section
namespace Learning
variable {X : Type*} {K : Set X} [Nonempty K] {v : X}

open scoped Classical in
/-- The point `v` as an element of `K`, or an arbitrary element of `K` if `v ∉ K`. -/
noncomputable def toSet (K : Set X) [Nonempty K] (v : X) : K :=
  if h : v ∈ K then ⟨v, h⟩ else Classical.arbitrary K

end Learning
end

-- ═══ Ito2026Adversarial.Mathlib.Analysis.Convex.FenchelConjugate ═══
@[expose] public section
open scoped RealInnerProductSpace
variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] {s t : Set E} {f : E → ℝ} {x θ : E}

/-- The Fenchel conjugate of `f` restricted to `s`: `θ ↦ sup_{x ∈ s} ⟪x, θ⟫ - f x`, with values in
`EReal` (`⊥` if `s` is empty, `⊤` if the supremum is infinite). -/
noncomputable def fenchelConjugateOn (s : Set E) (f : E → ℝ) (θ : E) : EReal :=
  ⨆ x : s, ((⟪(x : E), θ⟫ - f x : ℝ) : EReal)

end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Online.Bandit.SimplexFTRL ═══
@[expose] public section
open MeasureTheory Finset
open scoped RealInnerProductSpace
namespace Learning
variable {ι : Type*} [Fintype ι]

/-- The value function `Φ(θ) = sup_{p ∈ simplex} ⟪p, θ⟫ + φ p` of FTRL with regularizer `φ`: the
Fenchel conjugate of `-φ` on the simplex. -/
noncomputable def ftrlValue (φ : EuclideanSpace ℝ ι → ℝ) (θ : EuclideanSpace ℝ ι) : ℝ :=
  (fenchelConjugateOn (simplex ι) (-φ) θ).toReal

/-- The FTRL distribution `argmax_{p ∈ simplex} ⟪p, θ⟫ + φ p`, defined as the gradient of the
value function `ftrlValue φ` at `θ` (an arbitrary element of the simplex where the value function
is not differentiable). -/
noncomputable def ftrlSimplex [Nonempty ι] (φ : EuclideanSpace ℝ ι → ℝ) (θ : EuclideanSpace ℝ ι) :
    simplex ι :=
  toSet (simplex ι) (gradient (ftrlValue φ) θ)

section Param
variable {F E : Type*} [NormedAddCommGroup F] [InnerProductSpace ℝ F] [CompleteSpace F] [MeasurableSpace F] [BorelSpace F] [SecondCountableTopology F] [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E] [MeasurableSpace E] [BorelSpace E] [SecondCountableTopology E]

/-- The gradient with respect to the second variable of a function `G : F × E → ℝ`, obtained by
restricting the joint Fréchet derivative to the second factor (zero where `G` is not
differentiable). -/
noncomputable def gradientSnd (G : F × E → ℝ) (q : F × E) : E :=
  (InnerProductSpace.toDual ℝ E).symm ((fderiv ℝ G q).comp (ContinuousLinearMap.inr ℝ F E))

/-- The value function of FTRL with a regularizer `φ β` depending on a parameter `β : F`, as a
function of `(β, θ)`. -/
noncomputable def ftrlValueParam (φ : F → EuclideanSpace ℝ ι → ℝ) (q : F × EuclideanSpace ℝ ι) :
    ℝ :=
  ftrlValue (φ q.1) q.2

/-- The FTRL distribution `argmax_{p ∈ simplex} ⟪p, θ⟫ + φ β p` for the regularizer `φ β`, defined
as the partial gradient in `θ` of the joint value function `ftrlValueParam φ` at `(β, θ)`. The
parameter `β` lives in an inner product space `F` (a real, or a vector of means). -/
noncomputable def ftrlSimplexParam [Nonempty ι] (φ : F → EuclideanSpace ℝ ι → ℝ)
    (q : F × EuclideanSpace ℝ ι) : simplex ι :=
  toSet (simplex ι) (gradientSnd (ftrlValueParam φ) q)

end Param

/-- The Tsallis entropy `φ_α(p) = (1 / α) ∑ i, (p i ^ α - p i)`, nonnegative and concave on the
simplex for `α ∈ (0, 1)`. -/
noncomputable def tsallisEntropy (α : ℝ) (p : EuclideanSpace ℝ ι) : ℝ :=
  α⁻¹ * ∑ i, (p i ^ α - p i)

end Learning
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.DesignMatrix ═══
@[expose] public section
open Matrix Real
open scoped RealInnerProductSpace
namespace Learning
variable {ι : Type*}

/-- The design matrix `x xᵀ` of a point `x`. -/
def outerSelf (x : EuclideanSpace ℝ ι) : Matrix ι ι ℝ :=
  Matrix.vecMulVec (WithLp.ofLp x) (WithLp.ofLp x)

variable [Fintype ι]
variable [DecidableEq ι]
variable {ι : Type*} {𝒳 : Set (EuclideanSpace ℝ ι)} {x : EuclideanSpace ℝ ι} {A : Matrix ι ι ℝ} {R : ℝ}
variable [Fintype ι]
variable [DecidableEq ι]
end Learning
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Game.ZeroSum ═══
@[expose] public section
open Finset
namespace Learning.ZeroSumGame
variable {𝒳 𝒴 : Type*} {u : 𝒳 → 𝒴 → ℝ} {x : 𝒳} {y : 𝒴}

/-- `(x, y)` is a strict pure-strategy Nash equilibrium of `u`: `u x' y < u x y < u x y'` for all
`x' ≠ x`, `y' ≠ y`. -/
def IsStrictPSNE (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) : Prop :=
  (∀ x' ≠ x, u x' y < u x y) ∧ ∀ y' ≠ y, u x y < u x y'

/-- The pure-strategy maximin value `v* = max_x min_y u x y`. -/
noncomputable def pureMaximin (u : 𝒳 → 𝒴 → ℝ) : ℝ := ⨆ x, ⨅ y, u x y

/-- The sub-optimality gap `Δʳ_{x'} = u x y - u x' y` of the row action `x'` at the equilibrium
`(x, y)`. -/
def rowGap (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) (x' : 𝒳) : ℝ := u x y - u x' y

/-- The sub-optimality gap `Δᶜ_{y'} = u x y' - u x y` of the column action `y'` at the
equilibrium `(x, y)`. -/
def colGap (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) (y' : 𝒴) : ℝ := u x y' - u x y

/-- The minimal row gap `Δʳ_min = min_{x' ≠ x} Δʳ_{x'}`. -/
noncomputable def rowGapMin (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) : ℝ :=
  ⨅ x' : {x' // x' ≠ x}, rowGap u x y x'

/-- The minimal column gap `Δᶜ_min = min_{y' ≠ y} Δᶜ_{y'}`. -/
noncomputable def colGapMin (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) : ℝ :=
  ⨅ y' : {y' // y' ≠ y}, colGap u x y y'

section Mixed
variable [Fintype 𝒳] [Fintype 𝒴]

/-- The expected utility `∑ x y, p x * q y * u x y` of the mixed strategies `p` and `q`. -/
def mixedUtility (u : 𝒳 → 𝒴 → ℝ) (p : EuclideanSpace ℝ 𝒳) (q : EuclideanSpace ℝ 𝒴) : ℝ :=
  ∑ x, ∑ y, p x * q y * u x y

/-- The mixed-strategy maximin value `max_p min_q u(p, q)`, which is the value `v^Nash` of the
Nash equilibria of the game (von Neumann's minimax theorem). -/
noncomputable def nashValue (u : 𝒳 → 𝒴 → ℝ) : ℝ :=
  ⨆ p : simplex 𝒳, ⨅ q : simplex 𝒴, mixedUtility u p q

/-- The gap `Δ^mix = v^Nash - v*` between the Nash value and the pure-strategy maximin value. -/
noncomputable def mixGap (u : 𝒳 → 𝒴 → ℝ) : ℝ := nashValue u - pureMaximin u

end Mixed
end Learning.ZeroSumGame
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Game.RepeatedGame ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset
open scoped ProbabilityTheory
namespace Learning.RepeatedGame
open ZeroSumGame
variable {𝒳 𝒴 : Type*} [MeasurableSpace 𝒳] [MeasurableSpace 𝒴]

/-- A player of the repeated game with actions `𝒳`, against an opponent with actions `𝒴`: an
algorithm that observes, after each round, the opponent's action and the reward. -/
abbrev Player (𝒳 𝒴 : Type*) [MeasurableSpace 𝒳] [MeasurableSpace 𝒴] :=
  Algorithm Unit 𝒳 (𝒴 × ℝ)

/-- A round `(x, (y, r))` seen from the opponent: `(y, (x, r))`. -/
def Round.swapPlayers (r : Round Unit 𝒳 (𝒴 × ℝ)) : Round Unit 𝒴 (𝒳 × ℝ) :=
  ((), r.feedback.1, (r.action, r.feedback.2))

/-- A history seen from the opponent. -/
def Hist.swapPlayers {n : ℕ} (h : Hist Unit 𝒳 (𝒴 × ℝ) n) : Hist Unit 𝒴 (𝒳 × ℝ) n :=
  fun i ↦ Round.swapPlayers (h i)

@[fun_prop]
lemma Hist.measurable_swapPlayers (n : ℕ) :
    Measurable (Hist.swapPlayers (𝒳 := 𝒳) (𝒴 := 𝒴) (n := n)) := sorry

/-- A reward kernel: the law of the reward of a round given the past rounds and the two actions
of the round. -/
abbrev RewardKernel (𝒳 𝒴 : Type*) [MeasurableSpace 𝒳] [MeasurableSpace 𝒴] :=
  (n : ℕ) → Kernel (Hist Unit 𝒳 (𝒴 × ℝ) n × 𝒳 × 𝒴) ℝ

/-- The reward kernel has conditional mean `u x y`: the noise `r_t - u x_t y_t` is a martingale
difference sequence. -/
def RewardKernel.HasMean (R : RewardKernel 𝒳 𝒴) (u : 𝒳 → 𝒴 → ℝ) : Prop :=
  ∀ n (h : Hist Unit 𝒳 (𝒴 × ℝ) n) x y, ∫ r, r ∂(R n (h, x, y)) = u x y

/-- The rewards lie in the set `s` almost surely. -/
def RewardKernel.RewardsIn (R : RewardKernel 𝒳 𝒴) (s : Set ℝ) : Prop :=
  ∀ n (h : Hist Unit 𝒳 (𝒴 × ℝ) n) x y, ∀ᵐ r ∂(R n (h, x, y)), r ∈ s

/-- The environment of the learner playing against the opponent `opp` with reward kernel `R`: the
feedback of a round is `(y, r)` with `y` drawn from the policy of `opp` on the past rounds (seen
from the opponent) and `r` from `R`. -/
noncomputable def gameEnv (opp : Player 𝒴 𝒳) (R : RewardKernel 𝒳 𝒴) [∀ n, IsMarkovKernel (R n)] :
    Environment Unit 𝒳 (𝒴 × ℝ) where
  obs _ := Kernel.const _ (Measure.dirac ())
  feedback n :=
    ((opp.policy n).comap
      (fun p : (Hist Unit 𝒳 (𝒴 × ℝ) n × Unit) × 𝒳 ↦ (Hist.swapPlayers p.1.1, ())) (by fun_prop))
    ⊗ₖ ((R n).comap (fun q : ((Hist Unit 𝒳 (𝒴 × ℝ) n × Unit) × 𝒳) × 𝒴 ↦ (q.1.1.1, q.1.2, q.2))
      (by fun_prop))

/-- An uninformed learner, which observes only the rewards, as a player of the repeated game
(ignoring the opponent's actions in the feedback). -/
noncomputable def Player.ofUninformed (alg : Algorithm Unit 𝒳 ℝ) : Player 𝒳 𝒴 :=
  alg.comapFeedback Prod.snd measurable_snd

section Regret
omit [MeasurableSpace 𝒳] [MeasurableSpace 𝒴]
variable {Ω : Type*} {mΩ : MeasurableSpace Ω}

/-- The pure-strategy maximin regret `PSMR_T = E[∑_{t<T} (v* - u x_t y_t)]` of the run `(X, Y)`
under `P`. -/
noncomputable def psmr (u : 𝒳 → 𝒴 → ℝ) (X : ℕ → Ω → 𝒳) (Y : ℕ → Ω → 𝒴) (P : Measure Ω)
    (T : ℕ) : ℝ :=
  P[fun ω ↦ ∑ t ∈ range T, (pureMaximin u - u (X t ω) (Y t ω))]

end Regret
section Counts
variable [DecidableEq 𝒳] [DecidableEq 𝒴]

/-- The number of rounds of the history `h` in which the pair `(x, y)` was played. -/
def histPairCount {n : ℕ} (h : Hist Unit 𝒳 (𝒴 × ℝ) n) (x : 𝒳) (y : 𝒴) : ℕ :=
  ∑ i, if (h i).action = x ∧ (h i).feedback.1 = y then 1 else 0

/-- The sum of the rewards of the rounds of the history `h` in which the pair `(x, y)` was
played. -/
def histPairSum {n : ℕ} (h : Hist Unit 𝒳 (𝒴 × ℝ) n) (x : 𝒳) (y : 𝒴) : ℝ :=
  ∑ i, if (h i).action = x ∧ (h i).feedback.1 = y then (h i).feedback.2 else 0

variable [MeasurableSingletonClass 𝒳] [MeasurableSingletonClass 𝒴]
variable {Ω : Type*} {mΩ : MeasurableSpace Ω}
end Counts
end Learning.RepeatedGame
end

-- ═══ Ito2026Adversarial.ILMTW2026.Setting ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset Learning Learning.ZeroSumGame Learning.RepeatedGame
  Matrix Real
open scoped RealInnerProductSpace
namespace Ito2026Adversarial
section MaximinUCB
variable {𝒳 𝒴 : Type*} [Fintype 𝒳] [Fintype 𝒴] [DecidableEq 𝒳] [DecidableEq 𝒴] [MeasurableSpace 𝒳] [MeasurableSpace 𝒴]

/-- The upper confidence bound `U(x, y)` of Maximin-UCB after the history `h`: `1` if `(x, y)`
was never played, and otherwise the empirical mean plus
`√((4 log(1/δ) + 2 log(1 + N(x, y))) / N(x, y))`. -/
noncomputable def ucbIndex (δ : ℝ) {n : ℕ} (h : Hist Unit 𝒳 (𝒴 × ℝ) n) (x : 𝒳) (y : 𝒴) : ℝ :=
  if histPairCount h x y = 0 then 1 else
    histPairSum h x y / histPairCount h x y
      + √((4 * log (1 / δ) + ((2 : ℕ) : ℝ) * log (1 + histPairCount h x y)) / histPairCount h x y)

variable [MeasurableSingletonClass 𝒳] [MeasurableSingletonClass 𝒴]
end MaximinUCB
section Bilinear
variable {ιx ιy : Type*} [Fintype ιx] [Fintype ιy]

/-- The bilinear utility `u(x, y) = ⟪x, A y⟫ = xᵀ A y`. -/
noncomputable def bilinearUtility (A : Matrix ιx ιy ℝ) (x : EuclideanSpace ℝ ιx)
    (y : EuclideanSpace ℝ ιy) : ℝ :=
  WithLp.ofLp x ⬝ᵥ (A *ᵥ WithLp.ofLp y)

variable {𝒳 𝒴 : Type*}

/-- The bilinear game with matrix `A` on the finite action sets `𝒳`, `𝒴` with features
`φ : 𝒳 → ℝ^{d_x}`, `ψ : 𝒴 → ℝ^{d_y}`: `u x y = ⟪φ x, A ψ y⟫`. -/
noncomputable def bilinearGame (φ : 𝒳 → EuclideanSpace ℝ ιx) (ψ : 𝒴 → EuclideanSpace ℝ ιy)
    (A : Matrix ιx ιy ℝ) : 𝒳 → 𝒴 → ℝ :=
  fun x y ↦ bilinearUtility A (φ x) (ψ y)

/-- The assumptions of the paper on a bilinear game: the actions have norm at most `1` and span
their spaces, and the matrix has operator norm at most `1` (so that `u x y ∈ [-1, 1]`). -/
structure IsBilinearGame (φ : 𝒳 → EuclideanSpace ℝ ιx) (ψ : 𝒴 → EuclideanSpace ℝ ιy)
    (A : Matrix ιx ιy ℝ) : Prop where
  norm_le_x : ∀ x, ‖φ x‖ ≤ 1
  norm_le_y : ∀ y, ‖ψ y‖ ≤ 1
  span_x : Submodule.span ℝ (Set.range φ) = ⊤
  span_y : Submodule.span ℝ (Set.range ψ) = ⊤
  opNorm_le : ∀ y : EuclideanSpace ℝ ιy,
    ‖(WithLp.toLp 2 (A *ᵥ WithLp.ofLp y) : EuclideanSpace ℝ ιx)‖ ≤ ‖y‖

/-- The design matrix `S(p) = E_{x ∼ p}[φ x (φ x)ᵀ]` of a distribution `p` on the action set
`𝒳` with features `φ`. -/
noncomputable def designOf [Fintype 𝒳] (φ : 𝒳 → EuclideanSpace ℝ ιx) (p : EuclideanSpace ℝ 𝒳) :
    Matrix ιx ιx ℝ :=
  ∑ x, p x • outerSelf (φ x)

/-- The exploration distribution `p₀` on `𝒳` has variance ratio `c`: `S(p₀)` is positive definite
and `⟪φ x, S(p₀)⁻¹ φ x⟫ ≤ c d_x` for all `x` (`c = 1` is achievable by the Kiefer–Wolfowitz
theorem). The positive definiteness is implicit in the paper; without it the inequality would
hold for `S(p₀)` singular, Lean's inverse of a singular matrix being `0`. -/
def HasVarianceRatio [Fintype 𝒳] [DecidableEq ιx] (φ : 𝒳 → EuclideanSpace ℝ ιx)
    (p₀ : EuclideanSpace ℝ 𝒳) (c : ℝ) : Prop :=
  (designOf φ p₀).PosDef ∧
    ∀ x, WithLp.ofLp (φ x) ⬝ᵥ (designOf φ p₀)⁻¹ *ᵥ WithLp.ofLp (φ x) ≤ c * Fintype.card ιx

end Bilinear
section SPM
variable {ιx : Type*} [Fintype ιx] {𝒳 : Type*} [Fintype 𝒳] [Nonempty 𝒳]

/-- The hybrid regularizer `β φ_α + βbar φ_{1-α}` of Tsallis-FTRL-SPM, with the learning rate `β`
as parameter. -/
noncomputable def hybridEntropy (α βbar β : ℝ) (p : EuclideanSpace ℝ 𝒳) : ℝ :=
  β * tsallisEntropy α p + βbar * tsallisEntropy (1 - α) p

/-- The FTRL distribution `p̂ = argmax_p ⟪p, G⟫ + β φ_α(p) + βbar φ_{1-α}(p)` from the state
`(G, β)`. -/
noncomputable def spmHat (α βbar : ℝ) (s : EuclideanSpace ℝ 𝒳 × ℝ) : simplex 𝒳 :=
  ftrlSimplexParam (hybridEntropy α βbar) (s.2, s.1)

/-- The coefficient `z = d (min {‖p‖_∞, 1 - ‖p‖_∞})^(1 - α) / (1 - α)`. -/
noncomputable def zCoef (α : ℝ) (d : ℕ) (p : EuclideanSpace ℝ 𝒳) : ℝ :=
  d * min (fun x ↦ p x).max (1 - (fun x ↦ p x).max) ^ (1 - α) / (1 - α)

/-- The distribution played by Tsallis-FTRL-SPM from the state `(G, β)`:
`(1 - γ) p̂ + γ p₀` with `γ = 4 c z / β`, for `d = d_x`. -/
noncomputable def spmDist (α βbar : ℝ) (d : ℕ) (p₀ : simplex 𝒳) (c : ℝ)
    (s : EuclideanSpace ℝ 𝒳 × ℝ) : simplex 𝒳 :=
  toSet (simplex 𝒳)
    ((1 - 4 * c * zCoef α d ((spmHat α βbar s : simplex 𝒳) : EuclideanSpace ℝ 𝒳) / s.2) •
        ((spmHat α βbar s : simplex 𝒳) : EuclideanSpace ℝ 𝒳)
      + (4 * c * zCoef α d ((spmHat α βbar s : simplex 𝒳) : EuclideanSpace ℝ 𝒳) / s.2) •
        (p₀ : EuclideanSpace ℝ 𝒳))

omit [Fintype ιx] in
@[fun_prop]
lemma measurable_spmDist (α βbar : ℝ) (d : ℕ) (p₀ : simplex 𝒳) (c : ℝ) :
    Measurable (spmDist α βbar d p₀ c) := sorry

variable [DecidableEq ιx] [MeasurableSpace 𝒳] [MeasurableSingletonClass 𝒳] (φ : 𝒳 → EuclideanSpace ℝ ιx)

/-- The reward estimate `g(x) = r ⟪φ x_t, S(p)⁻¹ φ x⟫` of a round played with the distribution
`p` (action `x_t`, reward `r`). -/
noncomputable def spmEstimate (p : simplex 𝒳) (r : Round Unit 𝒳 ℝ) : EuclideanSpace ℝ 𝒳 :=
  WithLp.toLp _ fun x ↦ r.feedback *
    (WithLp.ofLp (φ r.action) ⬝ᵥ (designOf φ p)⁻¹ *ᵥ WithLp.ofLp (φ x))

/-- The state update of Tsallis-FTRL-SPM: `(G, β) ↦ (G + g, β + z / (β φ_α(p̂)))`. -/
noncomputable def spmUpdate (α βbar : ℝ) (p₀ : simplex 𝒳) (c : ℝ)
    (s : EuclideanSpace ℝ 𝒳 × ℝ) (r : Round Unit 𝒳 ℝ) : EuclideanSpace ℝ 𝒳 × ℝ :=
  (s.1 + spmEstimate φ (spmDist α βbar (Fintype.card ιx) p₀ c s) r,
    s.2 + zCoef α (Fintype.card ιx) ((spmHat α βbar s : simplex 𝒳) : EuclideanSpace ℝ 𝒳)
      / (s.2 * tsallisEntropy α ((spmHat α βbar s : simplex 𝒳) : EuclideanSpace ℝ 𝒳)))

@[fun_prop]
lemma measurable_spmUpdate {X : Type*} [MeasurableSpace X] (α βbar : ℝ) (p₀ : simplex 𝒳) (c : ℝ)
    {s : X → EuclideanSpace ℝ 𝒳 × ℝ} {r : X → Round Unit 𝒳 ℝ} (hs : Measurable s)
    (hr : Measurable r) : Measurable fun x ↦ spmUpdate φ α βbar p₀ c (s x) (r x) := sorry

/-- **Algorithm 3** (Tsallis-FTRL with stability-penalty matching, Ito et al. 2024) with
Tsallis parameter `α`, initial learning rate `β₁`, penalty coefficient `βbar`, exploration
distribution `p₀` with variance ratio `c`, as an uninformed algorithm on the action set `𝒳` with
features `φ`: the stateful algorithm with state `(G_n, β_n)` updated by `spmUpdate`, sampling
from `spmDist` of the state. -/
noncomputable def tsallisSPM (α β₁ βbar : ℝ) (p₀ : simplex 𝒳) (c : ℝ) : Algorithm Unit 𝒳 ℝ :=
  Algorithm.stateful (0, β₁) (fun _ ↦ spmUpdate φ α βbar p₀ c) (by fun_prop) fun _ ↦
    (simplexKernel 𝒳).comap (fun q ↦ spmDist α βbar (Fintype.card ιx) p₀ c q.1) (by fun_prop)

/-- The Tsallis parameter `α = 1 - 1 / (4 log m_x)` of Theorem 5. -/
noncomputable def spmAlpha (mx : ℕ) : ℝ := 1 - 1 / (4 * log mx)

/-- The initial learning rate `β₁ = 8 c d_x / (1 - α)` of Theorem 5. -/
noncomputable def spmBeta₁ (c : ℝ) (dx : ℕ) (α : ℝ) : ℝ := 8 * c * dx / (1 - α)

/-- The penalty coefficient `βbar = 32 d_x / ((1 - α)² β₁)` of Theorem 5. -/
noncomputable def spmBetaBar (dx : ℕ) (α β₁ : ℝ) : ℝ := 32 * dx / ((1 - α) ^ 2 * β₁)

/-- Tsallis-FTRL-SPM with the parameters of Theorem 5: `α = 1 - 1 / (4 log m_x)`,
`β₁ = 8 c d_x / (1 - α)`, `βbar = 32 d_x / ((1 - α)² β₁)`, for the exploration distribution `p₀`
with variance ratio `c`. -/
noncomputable def tsallisSPMPaper (c : ℝ) (p₀ : simplex 𝒳) : Algorithm Unit 𝒳 ℝ :=
  tsallisSPM φ (spmAlpha (Fintype.card 𝒳))
    (spmBeta₁ c (Fintype.card ιx) (spmAlpha (Fintype.card 𝒳)))
    (spmBetaBar (Fintype.card ιx) (spmAlpha (Fintype.card 𝒳))
      (spmBeta₁ c (Fintype.card ιx) (spmAlpha (Fintype.card 𝒳)))) p₀ c

end SPM
end Ito2026Adversarial
end

-- ═══ Ito2026Adversarial.ILMTW2026.Theorem5 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset Real Learning Learning.ZeroSumGame
  Learning.RepeatedGame Matrix
universe u
namespace Ito2026Adversarial

/-- **Theorem 5** (Ito, Luo, Maiti, Tsuchiya, Wu 2026). For every variance ratio `c > 0` there is
a constant `C` such that for every bilinear game (`IsBilinearGame`) with `m_x ≥ 2` actions of the
learner, every exploration distribution `p₀` of variance ratio `c`, every adaptive adversary and
every reward noise with conditional mean `u` and rewards in `[-1, 1]`, the run of
Tsallis-FTRL-SPM with the parameters of the theorem satisfies
`PSMR_T ≤ C (√(T d_x log m_x) + m_x log² m_x)`; moreover
`PSMR_T ≤ C (d_x log m_x (1 + log T) (1 + 1 / Δᶜ_min) / Δʳ_min + m_x log² m_x)` if `(x*, y*)` is a
strict PSNE and `PSMR_T ≤ C (d_x log m_x / Δ^mix + m_x log² m_x)` if `Δ^mix > 0`.

As for Theorem 1, the second bound is the form given by the proof (the paper's
`O(d_x log m_x log T / (Δʳ_min Δᶜ_min) + m_x log² m_x)` follows for `m_y ≥ 2` and `T ≥ 2`, and is
false in Lean for `m_y = 1`), and the third is stated for `Δ^mix > 0`, which the paper deduces
from the absence of PSNE (not true in general) and which is all its proof uses. The variance ratio
`HasVarianceRatio` includes the invertibility of `S(p₀)`. The additive term is `m_x log² m_x`, not
the paper's `m_x log m_x` (see the module docstring). -/
theorem forall_exists_psmr_tsallisSPMPaper_le :
    ∀ c : ℝ, 0 < c → ∃ C : ℝ, 0 < C ∧
      ∀ {mx my dx dy : ℕ} [NeZero mx] [NeZero my] (φ : Fin mx → EuclideanSpace ℝ (Fin dx))
        (ψ : Fin my → EuclideanSpace ℝ (Fin dy)) (A : Matrix (Fin dx) (Fin dy) ℝ),
        IsBilinearGame φ ψ A → 2 ≤ mx →
      ∀ (p₀ : simplex (Fin mx)), HasVarianceRatio φ p₀ c →
      ∀ (opp : Player (Fin my) (Fin mx)) (R : RewardKernel (Fin mx) (Fin my))
        [∀ n, IsMarkovKernel (R n)],
      RewardKernel.HasMean R (bilinearGame φ ψ A) → RewardKernel.RewardsIn R (Set.Icc (-1) 1) →
      ∀ {Ω : Type u} {_mΩ : MeasurableSpace Ω} (P : Measure Ω) [IsProbabilityMeasure P]
        (X : ℕ → Ω → Fin mx) (Y : ℕ → Ω → Fin my) (Rw : ℕ → Ω → ℝ),
      IsAlgEnvSeq (fun _ _ ↦ ()) X (fun t ω ↦ (Y t ω, Rw t ω))
        (Player.ofUninformed (tsallisSPMPaper φ c p₀)) (gameEnv opp R) P →
      ∀ T : ℕ,
        psmr (bilinearGame φ ψ A) X Y P T ≤
          C * (√(T * dx * log mx) + mx * log mx ^ 2) ∧
        (∀ x₀ y₀, IsStrictPSNE (bilinearGame φ ψ A) x₀ y₀ →
          psmr (bilinearGame φ ψ A) X Y P T ≤
            C * (dx * log mx * (1 + log T) * (1 + 1 / colGapMin (bilinearGame φ ψ A) x₀ y₀)
              / rowGapMin (bilinearGame φ ψ A) x₀ y₀ + mx * log mx ^ 2)) ∧
        (0 < mixGap (bilinearGame φ ψ A) →
          psmr (bilinearGame φ ψ A) X Y P T ≤
            C * (dx * log mx / mixGap (bilinearGame φ ψ A) + mx * log mx ^ 2)) := sorry

end Ito2026Adversarial
end
