module

public import Mathlib.Probability.Kernel.Basic
public import Mathlib.Probability.Kernel.IonescuTulcea.Traj
public import Mathlib.Probability.Process.FiniteDimensionalLaws
public import Mathlib.Probability.HasCondDistrib
public import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
public import Mathlib.Probability.Independence.Basic
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Measure.SubFinite
public import Mathlib.Probability.Kernel.RadonNikodym
public import Mathlib.MeasureTheory.MeasurableSpace.Embedding
public import Mathlib.Order.Restriction
public import Mathlib.Probability.Kernel.IonescuTulcea.Maps
public import Mathlib.Analysis.Normed.Ring.Basic
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
public import Mathlib.MeasureTheory.Order.Lattice
public import Mathlib.CategoryTheory.Countable
public import Mathlib.MeasureTheory.Constructions.Polish.Basic
public import Mathlib.Order.CompletePartialOrder
public import Mathlib.Data.Matrix.Mul
public import Mathlib.Order.ConditionallyCompleteLattice.Finset
public import Mathlib.Analysis.Convex.Basic
public import Mathlib.Analysis.InnerProductSpace.PiL2
public import Mathlib.Analysis.Normed.Lp.MeasurableSpace
public import Mathlib.Geometry.Convex.ConvexSpace.CompactSpaceStdSimplex
public import Mathlib.Probability.Kernel.Composition.CompProd
public import Mathlib.Probability.Kernel.Composition.MapComap
public import Mathlib.Algebra.BigOperators.Intervals
public import Mathlib.Analysis.Calculus.Gradient.Basic
public import Mathlib.Analysis.Calculus.LineDeriv.Basic
public import Mathlib.Analysis.Convex.Function
public import Mathlib.Topology.Algebra.Module.ContinuousLinearMap.PiProd
public import Mathlib.Analysis.SpecialFunctions.Log.Basic
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Inner
public import Mathlib.Probability.Distributions.Bernoulli
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Analysis.Matrix.MeasurableSpace
public import Mathlib.Analysis.RCLike.Lemmas
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Complex
public import Mathlib.MeasureTheory.Group.Arithmetic
public import Mathlib.Topology.Instances.Matrix
public import Mathlib.LinearAlgebra.Matrix.PosDef
public import Mathlib.Analysis.Matrix.Order
public import Mathlib.Analysis.CStarAlgebra.Matrix
public import Mathlib.Analysis.InnerProductSpace.Adjoint
public import Mathlib.Analysis.Convex.Hull
public import Mathlib.LinearAlgebra.Matrix.SchurComplement
public import Mathlib.Analysis.Convex.Caratheodory
public import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
public import Mathlib.Topology.Algebra.Ring.Real
public import Mathlib.Analysis.SpecialFunctions.Pow.Real
public import Mathlib.MeasureTheory.Constructions.BorelSpace.ContinuousLinearMap
public import Mathlib.MeasureTheory.Function.SpecialFunctions.Basic
public import Mathlib.Analysis.InnerProductSpace.Basic
public import Mathlib.Data.EReal.Basic
public import Mathlib.Analysis.Calculus.FDeriv.Measurable
public import Mathlib.Algebra.BigOperators.Field
public import Mathlib.Probability.IdentDistrib
public import Mathlib.Probability.Independence.InfinitePi
public import Mathlib.MeasureTheory.Measure.GiryMonad
public import Mathlib.MeasureTheory.Measure.Dirac.Basic
public import Mathlib.MeasureTheory.Measure.Dirac.Def
public import Mathlib.MeasureTheory.Constructions.BorelSpace.Order
public import Mathlib.Probability.Moments.SubGaussian
public import Mathlib.MeasureTheory.Integral.Lebesgue.Add
public import Mathlib.Probability.Process.Filtration
public import Mathlib.Analysis.SpecialFunctions.Gaussian.FourierTransform
public import Mathlib.MeasureTheory.Measure.Lebesgue.EqHaar

/-! # Standalone extraction for `Ito2026Adversarial.exists_psmr_maximinUCB_le`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by ChallengeGen. -/

set_option quotPrecheck false

-- The options the project is built with.
set_option autoImplicit false
set_option relaxedAutoImplicit false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Real
end Real
namespace Finset
end Finset
namespace Learning
end Learning
namespace Function
end Function
namespace Learning.ZeroSumGame
end Learning.ZeroSumGame
namespace Learning.RepeatedGame
end Learning.RepeatedGame
namespace Matrix
end Matrix
namespace Ito2026Adversarial
end Ito2026Adversarial

-- ═══ LeanMachineLearning.SequentialLearning.Algorithm ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- One round of interaction: an observation, then an action, then a feedback. -/
abbrev Round (𝓞 𝓐 𝓨 : Type*) := 𝓞 × 𝓐 × 𝓨

/-- The action of a round. -/
def Round.action (r : Round 𝓞 𝓐 𝓨) : 𝓐 := r.2.1

/-- The feedback of a round. -/
def Round.feedback (r : Round 𝓞 𝓐 𝓨) : 𝓨 := r.2.2

/-- History of `n` complete rounds; `n = 0` is the empty history. -/
abbrev Hist (𝓞 𝓐 𝓨 : Type*) (n : ℕ) := Fin n → Round 𝓞 𝓐 𝓨

/-- A stochastic, sequential algorithm.
At each round, it sees an observation in `𝓞`, then takes an action in `𝓐`, and finally receives
feedback in `𝓨`. The action is a random function of the past rounds and the current observation. -/
@[ext]
structure Algorithm (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the action of round `n` given the past rounds and the current observation. -/
  policy : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n × 𝓞) 𝓐
  /-- The policy is a Markov kernel. -/
  [isMarkovKernel_policy : ∀ n, IsMarkovKernel (policy n)]

instance instIsMarkovKernelProdHistPolicy (alg : Algorithm 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (alg.policy n) :=
  alg.isMarkovKernel_policy n

/-- A stochastic environment.
At each round, an observation is drawn prior to the algorithm taking an action. Then the environment
provides feedback based on the observation and the action. -/
@[ext]
structure Environment (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the observation of round `n` given the past rounds. -/
  obs : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n) 𝓞
  /-- Law of the feedback of round `n` given the past rounds, the observation and the action. -/
  feedback : (n : ℕ) → Kernel ((Hist 𝓞 𝓐 𝓨 n × 𝓞) × 𝓐) 𝓨
  /-- The observation kernel is a Markov kernel. -/
  [isMarkovKernel_obs : ∀ n, IsMarkovKernel (obs n)]
  /-- The feedback kernel is a Markov kernel. -/
  [isMarkovKernel_feedback : ∀ n, IsMarkovKernel (feedback n)]

section IsAlgEnvSeq
variable {O : ℕ → Ω → 𝓞} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨} {P : Measure Ω} [IsFiniteMeasure P] {N : ℕ}

/-- History of the algorithm-environment sequence before time `n`: the rounds at
times `0, ..., n - 1`. -/
def history (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) : Hist 𝓞 𝓐 𝓨 n :=
  fun i ↦ (O i ω, A i ω, Y i ω)

/-- An algorithm-environment sequence: a sequence of observations, actions and feedbacks generated
by an algorithm interacting with an environment. -/
structure IsAlgEnvSeq
    (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)
    (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨)
    (P : Measure Ω) [IsFiniteMeasure P] : Prop where
  /-- The observation sequence is measurable. -/
  measurable_obs n : Measurable (O n) := by fun_prop
  /-- The action sequence is measurable. -/
  measurable_action n : Measurable (A n) := by fun_prop
  /-- The feedback sequence is measurable. -/
  measurable_feedback n : Measurable (Y n) := by fun_prop
  /-- The observation at time `n` has the correct conditional distribution given the history. -/
  hasCondDistrib_obs n :
    HasCondDistrib (O n) (history O A Y n) (env.obs n) P
  /-- The action at time `n` has the correct conditional distribution given the history and the
  observation at time `n`. -/
  hasCondDistrib_action n :
    HasCondDistrib (A n) (fun ω ↦ (history O A Y n ω, O n ω)) (alg.policy n) P
  /-- The feedback at time `n` has the correct conditional distribution given the history, the
  observation and the action at time `n`. -/
  hasCondDistrib_feedback n :
    HasCondDistrib (Y n) (fun ω ↦ ((history O A Y n ω, O n ω), A n ω)) (env.feedback n) P

end IsAlgEnvSeq
end Learning
end

-- ═══ LeanMachineLearning.SequentialLearning.Deterministic ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓞 𝓐 𝓨 : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨}
variable {nextA : (n : ℕ) → (Hist 𝓞 𝓐 𝓨 n × 𝓞) → 𝓐} {h_next : ∀ n, Measurable (nextA n)} {env : Environment 𝓞 𝓐 𝓨} {obs : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n) 𝓞} [∀ n, IsMarkovKernel (obs n)] {f : (n : ℕ) → ((Hist 𝓞 𝓐 𝓨 n × 𝓞) × 𝓐) → 𝓨} {hf : ∀ n, Measurable (f n)}

/-- A deterministic algorithm, which chooses the action given by the function `nextA`.
The initial action is `fun o ↦ nextA 0 (default, o)`. -/
@[simps]
noncomputable
def Algorithm.deterministic (nextA : (n : ℕ) → (Hist 𝓞 𝓐 𝓨 n × 𝓞) → 𝓐)
    (h_next : ∀ n, Measurable (nextA n)) :
    Algorithm 𝓞 𝓐 𝓨 where
  policy n := Kernel.deterministic (nextA n) (h_next n)

end Learning
end

-- ═══ LeanMachineLearning.ForMathlib.MeasureTheory.Order.Lattice ═══
@[expose] public section
open Finset
variable {α δ : Type*} [MeasurableSpace δ] [SemilatticeInf α] {m : MeasurableSpace α} [MeasurableInf₂ α]
attribute [to_dual existing] MeasurableInf₂
end

-- ═══ LeanMachineLearning.ForMathlib.MeasureTheory.Order.MeasurableArg ═══
@[expose] public section
open Finset
variable {ι α : Type*} [LinearOrder α] [Fintype ι] [Nonempty ι] (f : ι → α)
namespace Function

/-- The maximum value of a tuple. -/
@[to_dual /-- The minimum value of a tuple. -/]
abbrev max : α := univ.sup' univ_nonempty f

end Function
section Argmax

@[to_dual]
lemma exists_argmax : ∃ i, f i = f.max := sorry

/-- The index of the maximum value of a tuple. -/
@[to_dual /-- The index of the minimum value of a tuple. -/]
noncomputable def argmax := (exists_argmax f).choose

variable [MeasurableSpace α]

@[to_dual (attr := fun_prop)]
lemma measurable_max [MeasurableSup₂ α] : Measurable (fun (t : ι → α) => t.max) := sorry

@[to_dual (attr := fun_prop)]
lemma measurable_argmax [MeasurableSpace ι] [MeasurableEq α] [MeasurableSup₂ α] :
    Measurable fun f : ι → α ↦ argmax f := sorry

end Argmax
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.SequentialLearning.Algorithms.Index ═══
@[expose] public section
open MeasureTheory ProbabilityTheory
namespace Learning
variable {𝓞 𝓐 𝓨 σ : Type*} [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] [MeasurableSpace σ] [Fintype 𝓐] [Nonempty 𝓐]

/-- The index algorithm with indices `idx n (h, o) a`: at round `n`, play an action maximizing
the index computed from the history `h` and the observation `o`. -/
noncomputable def Algorithm.index (idx : (n : ℕ) → Hist 𝓞 𝓐 𝓨 n × 𝓞 → 𝓐 → ℝ)
    (hidx : ∀ n, Measurable (idx n)) : Algorithm 𝓞 𝓐 𝓨 :=
  Algorithm.deterministic (fun n p ↦ argmax (idx n p)) fun n ↦ measurable_argmax.comp (hidx n)

end Learning
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Game.ZeroSum ═══
@[expose] public section
open Finset
namespace Learning.ZeroSumGame
variable {𝒳 𝒴 : Type*} {u : 𝒳 → 𝒴 → ℝ} {x : 𝒳} {y : 𝒴}

/-- The pure-strategy maximin value `v* = max_x min_y u x y`. -/
noncomputable def pureMaximin (u : 𝒳 → 𝒴 → ℝ) : ℝ := ⨆ x, ⨅ y, u x y

/-- The gap `Δ_{xy} = v* - u x y` of the action pair `(x, y)` to the pure-strategy maximin value
(possibly negative). -/
noncomputable def pairGap (u : 𝒳 → 𝒴 → ℝ) (x : 𝒳) (y : 𝒴) : ℝ := pureMaximin u - u x y

end Learning.ZeroSumGame
end

-- ═══ Ito2026Adversarial.LeanMachineLearning.Game.RepeatedGame ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset
open scoped ProbabilityTheory
namespace Learning.RepeatedGame
open ZeroSumGame
variable {𝒳 𝒴 : Type*} [MeasurableSpace 𝒳] [MeasurableSpace 𝒴]

/-- A player of the repeated game with actions `𝒳`, against an opponent with actions `𝒴`: an
algorithm that observes, after each round, the opponent's action and the reward. -/
abbrev Player (𝒳 𝒴 : Type*) [MeasurableSpace 𝒳] [MeasurableSpace 𝒴] :=
  Algorithm Unit 𝒳 (𝒴 × ℝ)

/-- A round `(x, (y, r))` seen from the opponent: `(y, (x, r))`. -/
def Round.swapPlayers (r : Round Unit 𝒳 (𝒴 × ℝ)) : Round Unit 𝒴 (𝒳 × ℝ) :=
  ((), r.feedback.1, (r.action, r.feedback.2))

/-- A history seen from the opponent. -/
def Hist.swapPlayers {n : ℕ} (h : Hist Unit 𝒳 (𝒴 × ℝ) n) : Hist Unit 𝒴 (𝒳 × ℝ) n :=
  fun i ↦ Round.swapPlayers (h i)

@[fun_prop]
lemma Hist.measurable_swapPlayers (n : ℕ) :
    Measurable (Hist.swapPlayers (𝒳 := 𝒳) (𝒴 := 𝒴) (n := n)) := sorry

/-- A reward kernel: the law of the reward of a round given the past rounds and the two actions
of the round. -/
abbrev RewardKernel (𝒳 𝒴 : Type*) [MeasurableSpace 𝒳] [MeasurableSpace 𝒴] :=
  (n : ℕ) → Kernel (Hist Unit 𝒳 (𝒴 × ℝ) n × 𝒳 × 𝒴) ℝ

/-- The reward kernel has conditional mean `u x y`: the noise `r_t - u x_t y_t` is a martingale
difference sequence. -/
def RewardKernel.HasMean (R : RewardKernel 𝒳 𝒴) (u : 𝒳 → 𝒴 → ℝ) : Prop :=
  ∀ n (h : Hist Unit 𝒳 (𝒴 × ℝ) n) x y, ∫ r, r ∂(R n (h, x, y)) = u x y

/-- The rewards lie in the set `s` almost surely. -/
def RewardKernel.RewardsIn (R : RewardKernel 𝒳 𝒴) (s : Set ℝ) : Prop :=
  ∀ n (h : Hist Unit 𝒳 (𝒴 × ℝ) n) x y, ∀ᵐ r ∂(R n (h, x, y)), r ∈ s

/-- The environment of the learner playing against the opponent `opp` with reward kernel `R`: the
feedback of a round is `(y, r)` with `y` drawn from the policy of `opp` on the past rounds (seen
from the opponent) and `r` from `R`. -/
noncomputable def gameEnv (opp : Player 𝒴 𝒳) (R : RewardKernel 𝒳 𝒴) [∀ n, IsMarkovKernel (R n)] :
    Environment Unit 𝒳 (𝒴 × ℝ) where
  obs _ := Kernel.const _ (Measure.dirac ())
  feedback n :=
    ((opp.policy n).comap
      (fun p : (Hist Unit 𝒳 (𝒴 × ℝ) n × Unit) × 𝒳 ↦ (Hist.swapPlayers p.1.1, ())) (by fun_prop))
    ⊗ₖ ((R n).comap (fun q : ((Hist Unit 𝒳 (𝒴 × ℝ) n × Unit) × 𝒳) × 𝒴 ↦ (q.1.1.1, q.1.2, q.2))
      (by fun_prop))

section Regret
omit [MeasurableSpace 𝒳] [MeasurableSpace 𝒴]
variable {Ω : Type*} {mΩ : MeasurableSpace Ω}

/-- The pure-strategy maximin regret `PSMR_T = E[∑_{t<T} (v* - u x_t y_t)]` of the run `(X, Y)`
under `P`. -/
noncomputable def psmr (u : 𝒳 → 𝒴 → ℝ) (X : ℕ → Ω → 𝒳) (Y : ℕ → Ω → 𝒴) (P : Measure Ω)
    (T : ℕ) : ℝ :=
  P[fun ω ↦ ∑ t ∈ range T, (pureMaximin u - u (X t ω) (Y t ω))]

end Regret
section Counts
variable [DecidableEq 𝒳] [DecidableEq 𝒴]

/-- The number of rounds of the history `h` in which the pair `(x, y)` was played. -/
def histPairCount {n : ℕ} (h : Hist Unit 𝒳 (𝒴 × ℝ) n) (x : 𝒳) (y : 𝒴) : ℕ :=
  ∑ i, if (h i).action = x ∧ (h i).feedback.1 = y then 1 else 0

/-- The sum of the rewards of the rounds of the history `h` in which the pair `(x, y)` was
played. -/
def histPairSum {n : ℕ} (h : Hist Unit 𝒳 (𝒴 × ℝ) n) (x : 𝒳) (y : 𝒴) : ℝ :=
  ∑ i, if (h i).action = x ∧ (h i).feedback.1 = y then (h i).feedback.2 else 0

variable [MeasurableSingletonClass 𝒳] [MeasurableSingletonClass 𝒴]
variable {Ω : Type*} {mΩ : MeasurableSpace Ω}
end Counts
end Learning.RepeatedGame
end

-- ═══ Ito2026Adversarial.ILMTW2026.Setting ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset Learning Learning.ZeroSumGame Learning.RepeatedGame
  Matrix Real
open scoped RealInnerProductSpace
namespace Ito2026Adversarial
section MaximinUCB
variable {𝒳 𝒴 : Type*} [Fintype 𝒳] [Fintype 𝒴] [DecidableEq 𝒳] [DecidableEq 𝒴] [MeasurableSpace 𝒳] [MeasurableSpace 𝒴]

/-- The upper confidence bound `U(x, y)` of Maximin-UCB after the history `h`: `1` if `(x, y)`
was never played, and otherwise the empirical mean plus
`√((4 log(1/δ) + 2 log(1 + N(x, y))) / N(x, y))`. -/
noncomputable def ucbIndex (δ : ℝ) {n : ℕ} (h : Hist Unit 𝒳 (𝒴 × ℝ) n) (x : 𝒳) (y : 𝒴) : ℝ :=
  if histPairCount h x y = 0 then 1 else
    histPairSum h x y / histPairCount h x y
      + √((4 * log (1 / δ) + ((2 : ℕ) : ℝ) * log (1 + histPairCount h x y)) / histPairCount h x y)

variable [MeasurableSingletonClass 𝒳] [MeasurableSingletonClass 𝒴]

omit [Fintype 𝒳] [Fintype 𝒴] in
@[fun_prop]
lemma measurable_ucbIndex (δ : ℝ) (n : ℕ) (x : 𝒳) (y : 𝒴) :
    Measurable fun h : Hist Unit 𝒳 (𝒴 × ℝ) n ↦ ucbIndex δ h x y := sorry

/-- **Algorithm 2** (Maximin-UCB) with confidence parameter `δ`: an informed deterministic player
which, at each round, plays the pure maximin action `ucbAction` of the upper confidence bounds of
the utilities of all action pairs (an index algorithm with index `x ↦ min_y U(x, y)`). -/
noncomputable def maximinUCB [Nonempty 𝒳] [Nonempty 𝒴] (δ : ℝ) : Player 𝒳 𝒴 :=
  Algorithm.index (fun _ p x ↦ (fun y ↦ ucbIndex δ p.1 x y).min) fun _ ↦ by fun_prop

end MaximinUCB
end Ito2026Adversarial
end

-- ═══ Ito2026Adversarial.ILMTW2026.Theorem4 ═══
@[expose] public section
open MeasureTheory ProbabilityTheory Finset Real Learning Learning.ZeroSumGame
  Learning.RepeatedGame
universe u
namespace Ito2026Adversarial

/-- **Theorem 4** (Ito, Luo, Maiti, Tsuchiya, Wu 2026). There is a universal constant `C` such
that for every game `u` with utilities in `[-1, 1]`, every adaptive adversary, every reward noise
with conditional mean `u` and rewards in `[-1, 1]` and every `T ≥ 2`, the run of Maximin-UCB
with `δ = 1 / T` satisfies both
`PSMR_T ≤ C (∑_{x, y : Δ_{xy} > 0} (Δ_{xy} + log T / Δ_{xy}) + m_x m_y)` and
`PSMR_T ≤ C √(m_x m_y T log T)`.

The paper states the first bound without the term `m_x m_y`, which its proof gets from the event
(of probability at most `m_x m_y / T`) where a confidence bound fails, and claims that this term is
absorbed by the big-O; this is not the case when few action pairs have a positive gap. -/
theorem exists_psmr_maximinUCB_le :
    ∃ C : ℝ, 0 < C ∧ ∀ {mx my : ℕ} [NeZero mx] [NeZero my] (u : Fin mx → Fin my → ℝ),
      (∀ x y, u x y ∈ Set.Icc (-1) 1) →
      ∀ (opp : Player (Fin my) (Fin mx)) (R : RewardKernel (Fin mx) (Fin my))
        [∀ n, IsMarkovKernel (R n)],
      RewardKernel.HasMean R u → RewardKernel.RewardsIn R (Set.Icc (-1) 1) →
      ∀ (T : ℕ), 2 ≤ T →
      ∀ {Ω : Type u} {_mΩ : MeasurableSpace Ω} (P : Measure Ω) [IsProbabilityMeasure P]
        (X : ℕ → Ω → Fin mx) (Y : ℕ → Ω → Fin my) (Rw : ℕ → Ω → ℝ),
      IsAlgEnvSeq (fun _ _ ↦ ()) X (fun t ω ↦ (Y t ω, Rw t ω)) (maximinUCB (1 / T))
        (gameEnv opp R) P →
        psmr u X Y P T ≤ C * (∑ x, ∑ y,
          (if 0 < pairGap u x y then pairGap u x y + log T / pairGap u x y else 0) + mx * my) ∧
        psmr u X Y P T ≤ C * √(mx * my * T * log T) := sorry

end Ito2026Adversarial
end
